// This file is part of Chaos Accelerator, licensed under the Common Public
// Attribution License, Version 1.0 (CPAL-1.0) - see LICENSE in the project
// root, or https://chaosaccelerator.com/license for a hosted copy.

// The double-float port of physics-gpu.js's GLSL physics library.
//
// WHY THIS EXISTS
// ---------------
// The first version of the df path carried extended precision only in the
// six per-body ACCUMULATORS, collapsing them to float32 for the actual
// collision and solver math on the theory that every geometric computation
// already works on small differences. Measurement said otherwise: coarsen
// any ONE of the six state fields by 16x and re-run 500 steps, and the
// answer moves by 1e-4 to 3e-4 - five of the six matter about equally. The
// float32 layer, not the accumulators, was setting the floor, and the real
// gain over float32 was about one decade rather than the four a bad metric
// had suggested. See the README's precision section for the numbers.
//
// So this file carries the whole step in df - collisions, both solvers,
// the funnel and splitter, and (in physics-gpu.js's generated step) Mutual
// Gravity's force sum. The float64 JS engine holds a proportional response
// down to a starting-position difference of ~1e-12, which is the target;
// float32 gives out around 1e-4.
//
// HOW TO READ IT
// --------------
// Every function here is a port of its namesake in physics-gpu.js's
// GLSL_LIBRARY, which is itself a line-for-line port of physics-engine.js.
// Same formulas, same variable names, same order of operations - only the
// spelling changes, because GLSL cannot give a user type operators.
// `a + b` becomes `dfAdd(a, b)` for scalars and `dv2Add(a, b)` for vectors;
// `dot(a, b)` becomes `dv2Dot(a, b)`; a float literal `1.0` becomes
// `vec2(1.0, 0.0)`.
//
// That makes this a THIRD hand-synced implementation of the same physics,
// alongside physics-engine.js and the float32 GLSL. The project already
// accepts that trade for the first two (see the README's "Two
// implementations, kept in lockstep on purpose"), and the same defense
// applies here: physics-tests.js cross-checks this against both of them,
// and the grid's own precision override renders the float32 and df passes
// at the same view so they can be compared directly.
//
// WHERE THIS IS NOT A STRAIGHT PORT
// ---------------------------------
// A df operation costs 10-20 float32 ones and a df sin/cos about forty of
// THOSE, where float32 has a hardware instruction - so work the float32
// library happily repeats is worth lifting out here. Every item below
// computes the SAME values the straight port would; it only computes each
// of them once. (The one exception is marked.)
//
//  - Segment geometry. A line's endpoints, direction and length are built
//    once per step into a DSegment and handed to every collision test that
//    line takes part in, instead of being re-derived (sin/cos included)
//    inside each one. For an ANCHORED line or trapezoid they are built once
//    per RUN: nothing ever moves it, so its geometry is a constant of the
//    pixel. physics-gpu.js's generated step owns where those live.
//  - Prepared hinges. No velocity iteration can change an angle, so the
//    rotated anchors and the inverted 2x2 effective-mass matrix are the
//    same on all 8 of them. dfPrepareHinge builds them once.
//  - Prepared contacts. A contact's normal and lever arms are fixed for the
//    step, so its effective mass is the same on every velocity iteration
//    and its positional push the same on every position iteration.
//    dfPrepareContact builds both once.
//  - Immovable sides. An anchored body (and the world pin) has zero inverse
//    mass, so every update to it multiplies by zero. The callers know which
//    side that is when the shader is generated, and say so, so the zero
//    work is never emitted.
//  - Trig across the position solve (THE EXCEPTION). The position solver
//    turns each hinged body by a tiny correction several times a step. The
//    straight port re-evaluates sin/cos from scratch before each one; here
//    each body's pair is carried through the loop and advanced by the
//    correction itself (dfSinCosNudge - angle-sum identities with a short
//    series for the small delta). That agrees with a fresh evaluation to
//    within a df ulp or two rather than bit for bit. OPTIONS.nudgeTrig
//    turns it off, which makes the whole file bit-identical to the
//    straight port again - physics-tests.js uses that to check the rest.
(function (global) {
  "use strict";

  var PhysicsDF = global.PhysicsDF;
  function d(n) { return PhysicsDF.num(n); }

  // Mirrors physics-gpu.js's own constants. Prefixed so a df shader can
  // include both libraries without colliding - the float32 one is still
  // pulled in for the per-pixel cascade's f32 helpers and for `Body`.
  var LINE_THICKNESS = 20;
  var LINE_PARALLEL_EPS = 0.05;
  var RESTITUTION_THRESHOLD = 30;
  var POSITION_SLOP = 0.01;
  var POSITION_PERCENT = 0.2;
  var FIXED_DT = 1 / 60;

  // Read when a shader is GENERATED, not baked into this file's text, so a
  // measurement page can flip one and rebuild. See the header for nudgeTrig.
  var OPTIONS = { nudgeTrig: true };

  function buildLibrary() {
    return [
    "// ---- Double-float physics: a port of GLSL_LIBRARY in physics-gpu.js ----",
    "",
    "const vec2 DF_LINE_THICKNESS = " + d(LINE_THICKNESS) + ";",
    "const vec2 DF_HALF_LINE_THICKNESS = " + d(LINE_THICKNESS * 0.5) + ";",
    "const vec2 DF_LINE_PARALLEL_EPS = " + d(LINE_PARALLEL_EPS) + ";",
    "const vec2 DF_RESTITUTION_THRESHOLD = " + d(RESTITUTION_THRESHOLD) + ";",
    "const vec2 DF_HALF_RESTITUTION_THRESHOLD = " + d(RESTITUTION_THRESHOLD * 0.5) + ";",
    "const vec2 DF_POSITION_SLOP = " + d(POSITION_SLOP) + ";",
    "const vec2 DF_POSITION_PERCENT = " + d(POSITION_PERCENT) + ";",
    // 1/60 is not representable in binary at all, so unlike the float32
    // library's DT this literal actually carries the extra digits.
    "const vec2 DF_DT = " + d(FIXED_DT) + ";",
    "const vec2 DF_GRAVITY = " + d(global.PhysicsEngine.GRAVITY) + ";",
    "const vec2 DF_ZERO = vec2(0.0, 0.0);",
    "const vec2 DF_ONE = vec2(1.0, 0.0);",
    "const vec2 DF_EPS9 = " + d(1e-9) + ";",
    "const vec2 DF_EPS12 = " + d(1e-12) + ";",
    "const vec2 DF_EPS6 = " + d(1e-6) + ";",
    "",
    "bool dfIsZero(vec2 a) { return a.x == 0.0 && a.y == 0.0; }",
    "",
    "// The six per-body fields that carry a fine distinction forward.",
    "struct DBody { vec2 x; vec2 y; vec2 angle; vec2 vx; vec2 vy; vec2 w; };",
    "",
    "// .point is carried for fidelity with the float32 Contact even though",
    "// nothing downstream reads it - both solvers work from .normal, .rA,",
    "// .rB and .penetration. Keeping it means this struct can be compared",
    "// field-for-field against the float32 one when the two disagree.",
    "// invMassSum/pushA/pushB are dfPrepareContact's: what the two solvers",
    "// would otherwise re-derive, identically, on every iteration.",
    "struct DContact { bool hit; DVec2 normal; DVec2 point; DVec2 rA; DVec2 rB; vec2 penetration; vec2 tHit;",
    "                  vec2 invMassSum; DVec2 pushA; DVec2 pushB; };",
    "struct DContactPair { DContact c0; DContact c1; };",
    "struct DClosestPair { DVec2 c1; DVec2 c2; };",
    "",
    "DContact dfNoContact() {",
    "  DContact c;",
    "  c.hit = false; c.normal = dv2Zero(); c.point = dv2Zero(); c.rA = dv2Zero(); c.rB = dv2Zero();",
    "  c.penetration = DF_ZERO; c.tHit = DF_ZERO;",
    "  c.invMassSum = DF_ZERO; c.pushA = dv2Zero(); c.pushB = dv2Zero();",
    "  return c;",
    "}",
    "",
    "// ---- Segments ----",
    "//",
    "// Everything the collision tests ever ask of a segment, built once: see",
    "// this file's header. physics-gpu.js's generated step decides how often",
    "// 'once' is - per step for anything that can move, per run for anything",
    "// anchored. g_dfStaticGeomReady is the flag that second case runs on; it",
    "// lives here rather than in the generated code so that every df shader",
    "// has it, including ones that declare bodies without ever stepping them.",
    "struct DSegment { DVec2 e0; DVec2 e1; DVec2 seg; vec2 lenSq; vec2 len; DVec2 dir; };",
    "bool g_dfStaticGeomReady = false;",
    "",
    "DSegment dfSegment(DVec2 e0, DVec2 e1) {",
    "  DSegment g;",
    "  g.e0 = e0; g.e1 = e1;",
    "  g.seg = dv2Sub(e1, e0);",
    "  g.lenSq = dv2LengthSq(g.seg);",
    "  g.len = dfSqrt(g.lenSq);",
    "  g.dir = dv2(DF_ONE, DF_ZERO);",
    "  if (dfGreater(g.len, DF_EPS9)) g.dir = dv2Scale(g.seg, dfDiv(DF_ONE, g.len));",
    "  return g;",
    "}",
    "",
    "// Both endpoints from one sin/cos. The float32 version calls",
    "// lineEndpoint0 and lineEndpoint1 separately, each doing its own",
    "// cos+sin; at df prices that would be four series evaluations where one",
    "// does.",
    "void dfLineEndpoints(DBody line, vec2 halfLen, out DVec2 e0, out DVec2 e1) {",
    "  vec2 sn, cs;",
    "  dfSinCos(line.angle, sn, cs);",
    "  vec2 dx = dfMul(cs, halfLen), dy = dfMul(sn, halfLen);",
    "  e0 = dv2(dfSub(line.x, dx), dfSub(line.y, dy));",
    "  e1 = dv2(dfAdd(line.x, dx), dfAdd(line.y, dy));",
    "}",
    "",
    "DSegment dfLineSegment(DBody line, vec2 halfLen) {",
    "  DVec2 e0, e1;",
    "  dfLineEndpoints(line, halfLen, e0, e1);",
    "  return dfSegment(e0, e1);",
    "}",
    "",
    "DVec2 dfClosestPointOnSegment(DSegment g, DVec2 point) {",
    "  vec2 t = dfGreater(g.lenSq, DF_EPS12) ? dfDiv(dv2Dot(dv2Sub(point, g.e0), g.seg), g.lenSq) : DF_ZERO;",
    "  t = dfClamp(t, DF_ZERO, DF_ONE);",
    "  return dv2Add(g.e0, dv2Scale(g.seg, t));",
    "}",
    "",
    "DClosestPair dfClosestPointsSegmentSegment(DSegment g1, DSegment g2) {",
    "  DVec2 p1 = g1.e0, p2 = g2.e0;",
    "  DVec2 d1 = g1.seg;",
    "  DVec2 d2 = g2.seg;",
    "  DVec2 r = dv2Sub(p1, p2);",
    "  vec2 a = g1.lenSq, e = g2.lenSq, f = dv2Dot(d2, r);",
    "  vec2 s, t;",
    "  if (!dfGreater(a, DF_EPS9) && !dfGreater(e, DF_EPS9)) {",
    "    s = DF_ZERO; t = DF_ZERO;",
    "  } else if (!dfGreater(a, DF_EPS9)) {",
    "    s = DF_ZERO; t = dfClamp(dfDiv(f, e), DF_ZERO, DF_ONE);",
    "  } else {",
    "    vec2 c = dv2Dot(d1, r);",
    "    if (!dfGreater(e, DF_EPS9)) {",
    "      t = DF_ZERO; s = dfClamp(dfDiv(dfNeg(c), a), DF_ZERO, DF_ONE);",
    "    } else {",
    "      vec2 b = dv2Dot(d1, d2);",
    "      vec2 denom = dfSub(dfMul(a, e), dfSqr(b));",
    "      s = !dfIsZero(denom) ? dfClamp(dfDiv(dfSub(dfMul(b, f), dfMul(c, e)), denom), DF_ZERO, DF_ONE) : DF_ZERO;",
    "      t = dfDiv(dfAdd(dfMul(b, s), f), e);",
    "      if (dfLess(t, DF_ZERO)) { t = DF_ZERO; s = dfClamp(dfDiv(dfNeg(c), a), DF_ZERO, DF_ONE); }",
    "      else if (dfGreater(t, DF_ONE)) { t = DF_ONE; s = dfClamp(dfDiv(dfSub(b, c), a), DF_ZERO, DF_ONE); }",
    "    }",
    "  }",
    "  DClosestPair result;",
    "  result.c1 = dv2Add(p1, dv2Scale(d1, s));",
    "  result.c2 = dv2Add(p2, dv2Scale(d2, t));",
    "  return result;",
    "}",
    "",
    "// Sweep primitives: earliest t in [0, dt] at which a point travelling",
    "// from p at velocity v first reaches distance R from the feature, or a",
    "// negative sentinel if that never happens inside the step.",
    "vec2 dfSweepPointSphere(DVec2 p, DVec2 v, DVec2 c, vec2 R, vec2 dt) {",
    "  DVec2 dvec = dv2Sub(p, c);",
    "  vec2 qc = dfSub(dv2LengthSq(dvec), dfSqr(R));",
    "  if (!dfGreater(qc, DF_ZERO)) return DF_ZERO;",
    "  vec2 qa = dv2LengthSq(v);",
    "  if (!dfGreater(qa, DF_EPS9)) return dfNeg(DF_ONE);",
    "  vec2 qb = dfMulPow2(dv2Dot(dvec, v), 2.0);",
    "  vec2 disc = dfSub(dfSqr(qb), dfMulPow2(dfMul(qa, qc), 4.0));",
    "  if (dfLess(disc, DF_ZERO)) return dfNeg(DF_ONE);",
    "  vec2 t = dfDiv(dfSub(dfNeg(qb), dfSqrt(disc)), dfMulPow2(qa, 2.0));",
    "  if (dfLess(t, DF_ZERO) || dfGreater(t, dt)) return dfNeg(DF_ONE);",
    "  return t;",
    "}",
    "",
    "vec2 dfSweepPointSlab(DVec2 p, DVec2 v, DVec2 e0, DVec2 dir, vec2 len, vec2 R, vec2 dt) {",
    "  DVec2 perp = dv2Perp(dir);",
    "  vec2 f0 = dv2Dot(dv2Sub(p, e0), perp);",
    "  vec2 fv = dv2Dot(v, perp);",
    "  vec2 t;",
    "  if (!dfGreater(dfAbs(f0), R)) {",
    "    t = DF_ZERO;",
    "  } else {",
    "    vec2 target = dfGreater(f0, DF_ZERO) ? R : dfNeg(R);",
    "    if (!dfGreater(dfAbs(fv), DF_EPS9)) return dfNeg(DF_ONE);",
    "    t = dfDiv(dfSub(target, f0), fv);",
    "    if (dfLess(t, DF_ZERO) || dfGreater(t, dt)) return dfNeg(DF_ONE);",
    "  }",
    "  vec2 s = dv2Dot(dv2Sub(dv2Add(p, dv2Scale(v, t)), e0), dir);",
    "  if (dfLess(s, DF_ZERO) || dfGreater(s, len)) return dfNeg(DF_ONE);",
    "  return t;",
    "}",
    "",
    // accel is the body's whole acceleration (see advanceVelocity's own
    // comment in physics-gpu.js): the df gravity constant in the uniform
    // case, and under Mutual Gravity the df force sum the generated step
    // builds - at the pass's own precision, like everything else here.
    "DVec2 dfAdvanceVelocity(DVec2 v, vec2 dt, DVec2 accel) {",
    "  v.x = dfAdd(v.x, dfMul(accel.x, dt));",
    "  v.y = dfAdd(v.y, dfMul(accel.y, dt));",
    "  vec2 sq = dv2LengthSq(v);",
    "  if (dfGreater(sq, dfSqr(DF_MAX_SPEED))) v = dv2Scale(v, dfDiv(DF_MAX_SPEED, dfSqrt(sq)));",
    "  return v;",
    "}",
    "",
    "DContact dfCollideCircleCircle(DBody a, vec2 ra, DBody b, vec2 rb) {",
    "  DVec2 dvec = dv2(dfSub(b.x, a.x), dfSub(b.y, a.y));",
    "  vec2 distSq = dv2LengthSq(dvec);",
    "  vec2 dist = dfSqrt(distSq);",
    "  vec2 rsum = dfAdd(ra, rb);",
    "  DContact c = dfNoContact();",
    "  if (!dfLess(dist, rsum)) {",
    "    // Not touching at the start of the step - solve for whether",
    "    // straight-line motion brings them together before DT elapses. See",
    "    // the float32 collideCircleCircle for why this sub-step solve is",
    "    // what keeps the bounce a continuous function of the start.",
    "    DVec2 vRel = dv2(dfSub(b.vx, a.vx), dfSub(b.vy, a.vy));",
    "    vec2 qa = dv2LengthSq(vRel);",
    "    vec2 qb = dfMulPow2(dv2Dot(dvec, vRel), 2.0);",
    "    vec2 qc = dfSub(distSq, dfSqr(rsum));",
    "    vec2 disc = dfSub(dfSqr(qb), dfMulPow2(dfMul(qa, qc), 4.0));",
    "    if (!dfGreater(qa, DF_EPS9) || dfLess(disc, DF_ZERO)) return c;",
    "    vec2 t = dfDiv(dfSub(dfNeg(qb), dfSqrt(disc)), dfMulPow2(qa, 2.0));",
    "    if (dfLess(t, DF_ZERO) || dfGreater(t, DF_DT)) return c;",
    "    DVec2 hitD = dv2Add(dvec, dv2Scale(vRel, t));",
    "    vec2 hitDist = dv2Length(hitD);",
    "    DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "    if (dfGreater(hitDist, DF_EPS9)) n = dv2Scale(hitD, dfDiv(DF_ONE, hitDist));",
    "    DVec2 posA = dv2Add(dv2(a.x, a.y), dv2Scale(dv2(a.vx, a.vy), t));",
    "    c.hit = true;",
    "    c.normal = n;",
    "    c.point = dv2Add(posA, dv2Scale(n, ra));",
    "    c.rA = dv2Scale(n, ra);",
    "    c.rB = dv2Neg(dv2Scale(n, rb));",
    "    c.penetration = DF_ZERO;",
    "    c.tHit = t;",
    "    return c;",
    "  }",
    "  DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist, DF_EPS9)) n = dv2Scale(dvec, dfDiv(DF_ONE, dist));",
    "  c.hit = true;",
    "  c.normal = n;",
    "  c.point = dv2(dfAdd(a.x, dfMul(n.x, ra)), dfAdd(a.y, dfMul(n.y, ra)));",
    "  c.rA = dv2Scale(n, ra);",
    "  c.rB = dv2Neg(dv2Scale(n, rb));",
    "  c.penetration = dfSub(rsum, dist);",
    "  c.tHit = DF_ZERO;",
    "  return c;",
    "}",
    "",
    "// Swept capsule (segment g, half-thickness halfThickness, moving at",
    "// constant velocity segVel, otherwise rigid) vs. circle - the port of",
    "// sweptCapsuleCircleContact, and shared the same way: a line's own body",
    "// (refCenter = its center) and every funnel/splitter edge (refCenter =",
    "// the TRAPEZOID's center, since rA is a lever arm on the whole body).",
    "DContact dfSweptCapsuleCircleContact(DSegment g, DVec2 segVel, DVec2 refCenter, DBody circle, vec2 radius, vec2 halfThickness) {",
    "  DVec2 p0 = dv2(circle.x, circle.y);",
    "  DVec2 vRel = dv2Sub(dv2(circle.vx, circle.vy), segVel);",
    "  vec2 rsum = dfAdd(halfThickness, radius);",
    "  DContact c = dfNoContact();",
    "",
    "  vec2 dist0 = dv2Length(dv2Sub(p0, dfClosestPointOnSegment(g, p0)));",
    "  vec2 tHit = DF_ZERO;",
    "",
    "  if (!dfLess(dist0, rsum)) {",
    "    vec2 best = dfNeg(DF_ONE);",
    "    vec2 tSlab = dfSweepPointSlab(p0, vRel, g.e0, g.dir, g.len, rsum, DF_DT);",
    "    if (!dfLess(tSlab, DF_ZERO)) best = tSlab;",
    "    vec2 tCap0 = dfSweepPointSphere(p0, vRel, g.e0, rsum, DF_DT);",
    "    if (!dfLess(tCap0, DF_ZERO) && (dfLess(best, DF_ZERO) || dfLess(tCap0, best))) best = tCap0;",
    "    vec2 tCap1 = dfSweepPointSphere(p0, vRel, g.e1, rsum, DF_DT);",
    "    if (!dfLess(tCap1, DF_ZERO) && (dfLess(best, DF_ZERO) || dfLess(tCap1, best))) best = tCap1;",
    "    if (dfLess(best, DF_ZERO)) return c;",
    "    tHit = best;",
    "  }",
    "",
    "  DVec2 pHit = dv2Add(p0, dv2Scale(vRel, tHit));",
    "  DVec2 closest = dfClosestPointOnSegment(g, pHit);",
    "  DVec2 dvec = dv2Sub(pHit, closest);",
    "  vec2 dist = dv2Length(dvec);",
    "  DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist, DF_EPS9)) n = dv2Scale(dvec, dfDiv(DF_ONE, dist));",
    "",
    "  // Everything above is in the segment's frame; its own translation",
    "  // over tHit shifts .point and its reference center equally, so it",
    "  // cancels out of rA.",
    "  DVec2 segOffset = dv2Scale(segVel, tHit);",
    "  DVec2 pt = dv2Add(closest, dv2Scale(n, halfThickness));",
    "",
    "  c.hit = true;",
    "  c.normal = n;",
    "  c.point = dv2Add(pt, segOffset);",
    "  c.rA = dv2Sub(pt, refCenter);",
    "  c.rB = dv2Neg(dv2Scale(n, radius));",
    "  c.penetration = dfMax(dfSub(rsum, dist), DF_ZERO);",
    "  c.tHit = tHit;",
    "  return c;",
    "}",
    "",
    "// line -> circle; normal points line -> circle. g is the line's own",
    "// segment, built by whoever calls this (see the header).",
    "DContact dfCollideLineCircle(DBody line, DSegment g, DBody circle, vec2 radius) {",
    "  return dfSweptCapsuleCircleContact(g, dv2(line.vx, line.vy), dv2(line.x, line.y), circle, radius, DF_HALF_LINE_THICKNESS);",
    "}",
    "",
    "DContactPair dfCollideLineLine(DBody lineA, DSegment gA, DBody lineB, DSegment gB) {",
    "  DVec2 eA0 = gA.e0, eB0 = gB.e0, eB1 = gB.e1;",
    "",
    "  DContactPair result;",
    "  result.c0 = dfNoContact();",
    "  result.c1 = dfNoContact();",
    "",
    "  // The float32 version normalizes by a length it first bumps to 1.0 when",
    "  // degenerate; a DSegment's own dir falls back to (1, 0) instead, which",
    "  // is what the capsule test wants. Put this function's convention back",
    "  // for the two cases where they differ.",
    "  DVec2 dirA = gA.dir;",
    "  vec2 lenA = gA.len;",
    "  if (dfLess(lenA, DF_EPS9)) { lenA = DF_ONE; dirA = gA.seg; }",
    "  else if (!dfGreater(lenA, DF_EPS9)) dirA = dv2Scale(gA.seg, dfDiv(DF_ONE, lenA));",
    "  DVec2 dirBn = gB.dir;",
    "  if (dfLess(gB.len, DF_EPS9)) dirBn = gB.seg;",
    "  else if (!dfGreater(gB.len, DF_EPS9)) dirBn = dv2Scale(gB.seg, dfDiv(DF_ONE, gB.len));",
    "  vec2 crossVal = dv2Cross(dirA, dirBn);",
    "",
    "  if (dfLess(dfAbs(crossVal), DF_LINE_PARALLEL_EPS)) {",
    "    DVec2 perp = dv2Perp(dirA);",
    "    vec2 offset = dv2Dot(dv2Sub(eB0, eA0), perp);",
    "    vec2 distP = dfAbs(offset);",
    "    if (dfLess(distP, DF_LINE_THICKNESS)) {",
    "      vec2 b0 = dv2Dot(dv2Sub(eB0, eA0), dirA);",
    "      vec2 b1 = dv2Dot(dv2Sub(eB1, eA0), dirA);",
    "      vec2 lo = dfMax(DF_ZERO, dfMin(b0, b1));",
    "      vec2 hi = dfMin(lenA, dfMax(b0, b1));",
    "      if (dfGreater(hi, lo)) {",
    "        vec2 sgn = !dfLess(offset, DF_ZERO) ? DF_ONE : dfNeg(DF_ONE);",
    "        DVec2 normal = dv2Scale(perp, sgn);",
    "        vec2 penetration = dfSub(DF_LINE_THICKNESS, distP);",
    "        DVec2 pOnA0 = dv2Add(eA0, dv2Scale(dirA, lo));",
    "        DVec2 pOnA1 = dv2Add(eA0, dv2Scale(dirA, hi));",
    "        DVec2 halfOffset = dv2Scale(perp, dfMulPow2(offset, 0.5));",
    "        DVec2 pt0 = dv2Add(pOnA0, halfOffset);",
    "        result.c0.hit = true;",
    "        result.c0.normal = normal;",
    "        result.c0.point = pt0;",
    "        result.c0.rA = dv2Sub(pt0, dv2(lineA.x, lineA.y));",
    "        result.c0.rB = dv2Sub(pt0, dv2(lineB.x, lineB.y));",
    "        result.c0.penetration = penetration;",
    "        result.c0.tHit = DF_ZERO;",
    "        if (dfGreater(dfSub(hi, lo), DF_EPS6)) {",
    "          DVec2 pt1 = dv2Add(pOnA1, halfOffset);",
    "          result.c1.hit = true;",
    "          result.c1.normal = normal;",
    "          result.c1.point = pt1;",
    "          result.c1.rA = dv2Sub(pt1, dv2(lineA.x, lineA.y));",
    "          result.c1.rB = dv2Sub(pt1, dv2(lineB.x, lineB.y));",
    "          result.c1.penetration = penetration;",
    "          result.c1.tHit = DF_ZERO;",
    "        }",
    "        return result;",
    "      }",
    "    }",
    "  }",
    "",
    "  DClosestPair cp = dfClosestPointsSegmentSegment(gA, gB);",
    "  DVec2 d2v = dv2Sub(cp.c2, cp.c1);",
    "  vec2 dist2 = dv2Length(d2v);",
    "  if (!dfLess(dist2, DF_LINE_THICKNESS)) return result;",
    "  DVec2 n2 = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist2, DF_EPS9)) n2 = dv2Scale(d2v, dfDiv(DF_ONE, dist2));",
    "  DVec2 pt2 = dv2MulPow2(dv2Add(cp.c1, cp.c2), 0.5);",
    "  result.c0.hit = true;",
    "  result.c0.normal = n2;",
    "  result.c0.point = pt2;",
    "  result.c0.rA = dv2Sub(pt2, dv2(lineA.x, lineA.y));",
    "  result.c0.rB = dv2Sub(pt2, dv2(lineB.x, lineB.y));",
    "  result.c0.penetration = dfSub(DF_LINE_THICKNESS, dist2);",
    "  result.c0.tHit = DF_ZERO;",
    "  return result;",
    "}",
    "",
    "// ---- Funnel and splitter: the port of the float32 trapezoid functions ----",
    "//",
    "// One DTrapezoid holds all four sides as segments plus the throat",
    "// center's offset from the body's own center, from a single sin/cos.",
    "// mouth runs mouthLeft -> mouthRight, throat throatLeft -> throatRight,",
    "// leg1 mouthLeft -> throatLeft and leg2 mouthRight -> throatRight - the",
    "// same endpoints, in the same order, physics-gpu.js's wallsFor() names.",
    "const vec2 DF_FUNNEL_MOUTH_HALF = " + d(global.PhysicsEngine.FUNNEL_MOUTH_HALF) + ";",
    "const vec2 DF_FUNNEL_THROAT_HALF = " + d(global.PhysicsEngine.FUNNEL_THROAT_HALF) + ";",
    "const vec2 DF_FUNNEL_HALF_HEIGHT = " + d(global.PhysicsEngine.FUNNEL_HALF_HEIGHT) + ";",
    "struct DTrapezoid { DSegment mouth; DSegment throat; DSegment leg1; DSegment leg2; DVec2 throatCenter; };",
    "DTrapezoid dfTrapezoid(DBody f, vec2 size) {",
    "  vec2 mh = dfMul(DF_FUNNEL_MOUTH_HALF, size), th = dfMul(DF_FUNNEL_THROAT_HALF, size), hh = dfMul(DF_FUNNEL_HALF_HEIGHT, size);",
    "  vec2 sn, cs;",
    "  dfSinCos(f.angle, sn, cs);",
    "  DVec2 c = dv2(f.x, f.y);",
    "  DVec2 mouthLeft = dv2Add(c, dv2RotateBy(dv2(dfNeg(mh), dfNeg(hh)), sn, cs));",
    "  DVec2 mouthRight = dv2Add(c, dv2RotateBy(dv2(mh, dfNeg(hh)), sn, cs));",
    "  DVec2 throatLeft = dv2Add(c, dv2RotateBy(dv2(dfNeg(th), hh), sn, cs));",
    "  DVec2 throatRight = dv2Add(c, dv2RotateBy(dv2(th, hh), sn, cs));",
    "  DTrapezoid t;",
    "  t.mouth = dfSegment(mouthLeft, mouthRight);",
    "  t.throat = dfSegment(throatLeft, throatRight);",
    "  t.leg1 = dfSegment(mouthLeft, throatLeft);",
    "  t.leg2 = dfSegment(mouthRight, throatRight);",
    "  t.throatCenter = dv2RotateBy(dv2(DF_ZERO, hh), sn, cs);",
    "  return t;",
    "}",
    "",
    "struct DMouthHit { bool hit; vec2 tHit; DVec2 target; };",
    "DMouthHit dfCollideFunnelMouthTHit(DBody funnel, DTrapezoid t, DBody circle, vec2 radius) {",
    "  DContact c = dfSweptCapsuleCircleContact(t.mouth, dv2(funnel.vx, funnel.vy), dv2(funnel.x, funnel.y), circle, radius, DF_HALF_LINE_THICKNESS);",
    "  DMouthHit m;",
    "  m.hit = false; m.tHit = DF_ZERO; m.target = dv2Zero();",
    "  if (!c.hit) return m;",
    "  m.hit = true;",
    "  m.tHit = c.tHit;",
    "  m.target = dv2Add(dv2Add(dv2(funnel.x, funnel.y), dv2Scale(dv2(funnel.vx, funnel.vy), c.tHit)), t.throatCenter);",
    "  return m;",
    "}",
    "",
    "struct DSplitHit { bool hit; vec2 tHit; DVec2 offset1; DVec2 offset2; };",
    "DSplitHit dfCollideSplitterShortSideTHit(DBody splitter, DTrapezoid t, DBody circle, vec2 radius) {",
    "  DSplitHit s;",
    "  s.hit = false; s.tHit = DF_ZERO; s.offset1 = dv2Zero(); s.offset2 = dv2Zero();",
    "  // Only a FRESH crossing splits - see the float32 version for why the",
    "  // guard has to sit ahead of the swept test.",
    "  DVec2 p0 = dv2(circle.x, circle.y);",
    "  DVec2 startClosest = dfClosestPointOnSegment(t.throat, p0);",
    "  if (dfLess(dv2Length(dv2Sub(p0, startClosest)), dfAdd(DF_HALF_LINE_THICKNESS, radius))) return s;",
    "  DContact c = dfSweptCapsuleCircleContact(t.throat, dv2(splitter.vx, splitter.vy), dv2(splitter.x, splitter.y), circle, radius, DF_HALF_LINE_THICKNESS);",
    "  if (!c.hit) return s;",
    "  DVec2 exitDir = dv2Sub(dv2MulPow2(dv2Add(t.mouth.e0, t.mouth.e1), 0.5), dv2MulPow2(dv2Add(t.throat.e0, t.throat.e1), 0.5));",
    "  vec2 exitLen = dv2Length(exitDir);",
    "  DVec2 exitUnit = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(exitLen, DF_EPS9)) exitUnit = dv2Scale(exitDir, dfDiv(DF_ONE, exitLen));",
    "  DVec2 clear = dv2Scale(exitUnit, dfAdd(DF_LINE_THICKNESS, dfMulPow2(radius, 2.0)));",
    "  s.hit = true;",
    "  s.tHit = c.tHit;",
    "  s.offset1 = dv2Add(dv2Sub(t.mouth.e0, t.throat.e0), clear);",
    "  s.offset2 = dv2Add(dv2Sub(t.mouth.e1, t.throat.e1), clear);",
    "  return s;",
    "}",
    "",
    "void dfApplyImpulse(inout DBody b, vec2 invMass, vec2 invInertia, DVec2 impulse, DVec2 r) {",
    "  b.vx = dfAdd(b.vx, dfMul(impulse.x, invMass));",
    "  b.vy = dfAdd(b.vy, dfMul(impulse.y, invMass));",
    "  b.w = dfAdd(b.w, dfMul(invInertia, dv2Cross(r, impulse)));",
    "}",
    "",
    "DVec2 dfVelocityAt(DBody b, DVec2 r) {",
    "  return dv2(dfSub(b.vx, dfMul(b.w, r.y)), dfAdd(b.vy, dfMul(b.w, r.x)));",
    "}",
    "",
    "// Everything about a contact that no solver iteration can change. Called",
    "// once per contact, right after detection.",
    "void dfPrepareContact(inout DContact c, vec2 invMassA, vec2 invInertiaA, vec2 invMassB, vec2 invInertiaB) {",
    "  if (!c.hit) return;",
    "  vec2 raCrossN = dv2Cross(c.rA, c.normal);",
    "  vec2 rbCrossN = dv2Cross(c.rB, c.normal);",
    "  c.invMassSum = dfAdd(dfAdd(invMassA, invMassB),",
    "                       dfAdd(dfMul(dfSqr(raCrossN), invInertiaA),",
    "                             dfMul(dfSqr(rbCrossN), invInertiaB)));",
    "  vec2 linearSum = dfAdd(invMassA, invMassB);",
    "  if (!dfGreater(linearSum, DF_ZERO)) return;",
    "  vec2 correction = dfMul(dfDiv(dfMax(dfSub(c.penetration, DF_POSITION_SLOP), DF_ZERO), linearSum), DF_POSITION_PERCENT);",
    "  c.pushA = dv2(dfMul(dfMul(c.normal.x, correction), invMassA), dfMul(dfMul(c.normal.y, correction), invMassA));",
    "  c.pushB = dv2(dfMul(dfMul(c.normal.x, correction), invMassB), dfMul(dfMul(c.normal.y, correction), invMassB));",
    "}",
    "",
    "// movesA/movesB are compile-time facts the generated step passes as",
    "// literals: false for an anchored body, whose inverse mass of zero turns",
    "// its half of the update into a multiply by zero.",
    "void dfSolveContactVelocity(inout DBody bodyA, vec2 invMassA, vec2 invInertiaA, bool movesA,",
    "                            inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, bool movesB,",
    "                            DContact contact) {",
    "  if (!contact.hit) return;",
    "  DVec2 n = contact.normal;",
    "",
    "  DVec2 vA = dfVelocityAt(bodyA, contact.rA);",
    "  DVec2 vB = dfVelocityAt(bodyB, contact.rB);",
    "  DVec2 rv = dv2Sub(vB, vA);",
    "  vec2 velAlongNormal = dv2Dot(rv, n);",
    "  if (dfGreater(velAlongNormal, DF_ZERO)) return;",
    "  if (!dfGreater(contact.invMassSum, DF_ZERO)) return;",
    "",
    "  vec2 e = dfSmoothstep(DF_HALF_RESTITUTION_THRESHOLD, DF_RESTITUTION_THRESHOLD, dfNeg(velAlongNormal));",
    "  vec2 j = dfDiv(dfNeg(dfMul(dfAdd(DF_ONE, e), velAlongNormal)), contact.invMassSum);",
    "  DVec2 impulse = dv2(dfMul(n.x, j), dfMul(n.y, j));",
    "  if (movesA) dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2Neg(impulse), contact.rA);",
    "  if (movesB) dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, contact.rB);",
    "  // Nothing along the tangent: every contact is frictionless.",
    "}",
    "",
    "void dfSolveContactPosition(inout DBody bodyA, bool movesA, inout DBody bodyB, bool movesB, DContact contact) {",
    "  if (!contact.hit) return;",
    "  if (movesA) { bodyA.x = dfSub(bodyA.x, contact.pushA.x); bodyA.y = dfSub(bodyA.y, contact.pushA.y); }",
    "  if (movesB) { bodyB.x = dfAdd(bodyB.x, contact.pushB.x); bodyB.y = dfAdd(bodyB.y, contact.pushB.y); }",
    "}",
    "",
    "// ---- The 2x2 effective-mass solve, split so its matrix can be kept ----",
    "struct DFactor2x2 { bool solvable; vec2 k11; vec2 k12; vec2 k22; vec2 invDet; };",
    "",
    "DFactor2x2 dfFactor2x2(vec2 mA, vec2 iA, DVec2 rA, vec2 mB, vec2 iB, DVec2 rB) {",
    "  DFactor2x2 k;",
    "  k.solvable = dfGreater(dfAdd(dfAdd(mA, mB), dfAdd(iA, iB)), DF_ZERO);",
    "  k.k11 = DF_ZERO; k.k12 = DF_ZERO; k.k22 = DF_ZERO; k.invDet = DF_ZERO;",
    "  if (!k.solvable) return k;",
    "  k.k11 = dfAdd(dfAdd(mA, mB), dfAdd(dfMul(iA, dfSqr(rA.y)), dfMul(iB, dfSqr(rB.y))));",
    "  k.k12 = dfSub(dfNeg(dfMul(iA, dfMul(rA.x, rA.y))), dfMul(iB, dfMul(rB.x, rB.y)));",
    "  k.k22 = dfAdd(dfAdd(mA, mB), dfAdd(dfMul(iA, dfSqr(rA.x)), dfMul(iB, dfSqr(rB.x))));",
    "  k.invDet = dfDiv(DF_ONE, dfSub(dfMul(k.k11, k.k22), dfSqr(k.k12)));",
    "  return k;",
    "}",
    "",
    "// The same matrix with side A immovable (mA = iA = 0): every A term is a",
    "// product with zero, so this is dfFactor2x2 with those terms deleted.",
    "DFactor2x2 dfFactor2x2OneSided(vec2 mB, vec2 iB, DVec2 rB) {",
    "  DFactor2x2 k;",
    "  k.solvable = dfGreater(dfAdd(mB, iB), DF_ZERO);",
    "  k.k11 = DF_ZERO; k.k12 = DF_ZERO; k.k22 = DF_ZERO; k.invDet = DF_ZERO;",
    "  if (!k.solvable) return k;",
    "  k.k11 = dfAdd(mB, dfMul(iB, dfSqr(rB.y)));",
    "  k.k12 = dfNeg(dfMul(iB, dfMul(rB.x, rB.y)));",
    "  k.k22 = dfAdd(mB, dfMul(iB, dfSqr(rB.x)));",
    "  k.invDet = dfDiv(DF_ONE, dfSub(dfMul(k.k11, k.k22), dfSqr(k.k12)));",
    "  return k;",
    "}",
    "",
    "DVec2 dfApply2x2(DFactor2x2 k, vec2 rhsX, vec2 rhsY) {",
    "  if (!k.solvable) return dv2Zero();",
    "  return dv2(dfMul(k.invDet, dfSub(dfMul(k.k22, rhsX), dfMul(k.k12, rhsY))),",
    "             dfMul(k.invDet, dfSub(dfMul(k.k11, rhsY), dfMul(k.k12, rhsX))));",
    "}",
    "",
    "// ---- Hinges ----",
    "//",
    "// snA/csA and snB/csB are each body's sin/cos, supplied by the caller.",
    "// No velocity iteration touches an angle, so the step computes the",
    "// rotated anchors and the factored matrix ONCE (dfPrepareHinge) and the",
    "// 8 iterations just apply them.",
    "struct DHingePre { DVec2 rA; DVec2 rB; DFactor2x2 k; };",
    "",
    "DHingePre dfPrepareHinge(vec2 invMassA, vec2 invInertiaA, DVec2 localAnchorA, vec2 snA, vec2 csA,",
    "                         vec2 invMassB, vec2 invInertiaB, DVec2 localAnchorB, vec2 snB, vec2 csB) {",
    "  DHingePre h;",
    "  h.rA = dv2RotateBy(localAnchorA, snA, csA);",
    "  h.rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  h.k = dfFactor2x2(invMassA, invInertiaA, h.rA, invMassB, invInertiaB, h.rB);",
    "  return h;",
    "}",
    "",
    "// Side A is the world pin: it never turns, so its anchor IS its lever",
    "// arm, and it never moves, so it drops out of the matrix.",
    "DHingePre dfPrepareWorldHinge(DVec2 anchorA, vec2 invMassB, vec2 invInertiaB, DVec2 localAnchorB, vec2 snB, vec2 csB) {",
    "  DHingePre h;",
    "  h.rA = anchorA;",
    "  h.rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  h.k = dfFactor2x2OneSided(invMassB, invInertiaB, h.rB);",
    "  return h;",
    "}",
    "",
    "void dfSolveHingeVelocity(inout DBody bodyA, vec2 invMassA, vec2 invInertiaA, bool movesA,",
    "                          inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, bool movesB, DHingePre h) {",
    "  DVec2 vA = dfVelocityAt(bodyA, h.rA);",
    "  DVec2 vB = dfVelocityAt(bodyB, h.rB);",
    "  DVec2 cdot = dv2Sub(vB, vA);",
    "  DVec2 impulse = dfApply2x2(h.k, dfNeg(cdot.x), dfNeg(cdot.y));",
    "  if (movesA) dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2Neg(impulse), h.rA);",
    "  if (movesB) dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, h.rB);",
    "}",
    "",
    "// The pin's own velocity is zero, so the constraint velocity is just B's.",
    "void dfSolveWorldHingeVelocity(inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, DHingePre h) {",
    "  DVec2 vB = dfVelocityAt(bodyB, h.rB);",
    "  DVec2 impulse = dfApply2x2(h.k, dfNeg(vB.x), dfNeg(vB.y));",
    "  dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, h.rB);",
    "}",
    "",
    "// Turn a body by delta and bring its carried sin/cos along - by the",
    "// short series when delta is small enough for it, from scratch when not.",
    "void dfTurn(inout vec2 angle, inout vec2 sn, inout vec2 cs, vec2 delta) {",
    "  angle = dfAdd(angle, delta);",
    OPTIONS.nudgeTrig
      ? "  if (!dfSinCosNudge(sn, cs, delta)) dfSinCos(angle, sn, cs);"
      : "  dfSinCos(angle, sn, cs);",
    "}",
    "",
    "// The position solve DOES rotate bodies, so unlike the velocity solver it",
    "// cannot be prepared once per step. Each body's sin/cos is instead",
    "// carried through the loop (inout) and advanced whenever this turns it.",
    "void dfSolveHingePosition(inout DBody bodyA, vec2 invMassA, vec2 invInertiaA, DVec2 localAnchorA, inout vec2 snA, inout vec2 csA, bool movesA,",
    "                          inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, DVec2 localAnchorB, inout vec2 snB, inout vec2 csB, bool movesB) {",
    "  DVec2 rA = dv2RotateBy(localAnchorA, snA, csA);",
    "  DVec2 rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  DVec2 worldA = dv2Add(dv2(bodyA.x, bodyA.y), rA);",
    "  DVec2 worldB = dv2Add(dv2(bodyB.x, bodyB.y), rB);",
    "  DVec2 c = dv2Sub(worldB, worldA);",
    "  DVec2 impulse = dfApply2x2(dfFactor2x2(invMassA, invInertiaA, rA, invMassB, invInertiaB, rB), dfNeg(c.x), dfNeg(c.y));",
    "  if (movesA) {",
    "    bodyA.x = dfSub(bodyA.x, dfMul(impulse.x, invMassA));",
    "    bodyA.y = dfSub(bodyA.y, dfMul(impulse.y, invMassA));",
    "    dfTurn(bodyA.angle, snA, csA, dfNeg(dfMul(invInertiaA, dv2Cross(rA, impulse))));",
    "  }",
    "  if (movesB) {",
    "    bodyB.x = dfAdd(bodyB.x, dfMul(impulse.x, invMassB));",
    "    bodyB.y = dfAdd(bodyB.y, dfMul(impulse.y, invMassB));",
    "    dfTurn(bodyB.angle, snB, csB, dfMul(invInertiaB, dv2Cross(rB, impulse)));",
    "  }",
    "}",
    "",
    "void dfSolveWorldHingePosition(DVec2 anchorA, inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, DVec2 localAnchorB, inout vec2 snB, inout vec2 csB) {",
    "  DVec2 rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  DVec2 worldB = dv2Add(dv2(bodyB.x, bodyB.y), rB);",
    "  DVec2 c = dv2Sub(worldB, anchorA);",
    "  DVec2 impulse = dfApply2x2(dfFactor2x2OneSided(invMassB, invInertiaB, rB), dfNeg(c.x), dfNeg(c.y));",
    "  bodyB.x = dfAdd(bodyB.x, dfMul(impulse.x, invMassB));",
    "  bodyB.y = dfAdd(bodyB.y, dfMul(impulse.y, invMassB));",
    "  dfTurn(bodyB.angle, snB, csB, dfMul(invInertiaB, dv2Cross(rB, impulse)));",
    "}",
    ].join("\n");
  }

  global.PhysicsGPUDF = {
    // A getter, not a baked string: OPTIONS is read each time a shader is
    // assembled, so flipping one takes effect on the next build.
    get GLSL_LIBRARY() { return buildLibrary(); },
    OPTIONS: OPTIONS,
  };
})(typeof window !== "undefined" ? window : globalThis);
