// This file is part of Chaos Accelerator, licensed under the Common Public
// Attribution License, Version 1.0 (CPAL-1.0) - see LICENSE in the project
// root, or https://chaosaccelerator.com/license for a hosted copy.

// The double-float port of physics-gpu.js's GLSL physics library.
//
// WHY THIS EXISTS
// ---------------
// The first version of the df path carried extended precision only in the
// six per-body ACCUMULATORS, collapsing them to float32 for the actual
// collision and solver math on the theory that every geometric computation
// already works on small differences. Measurement said otherwise: coarsen
// any ONE of the six state fields by 16x and re-run 500 steps, and the
// answer moves by 1e-4 to 3e-4 - five of the six matter about equally. The
// float32 layer, not the accumulators, was setting the floor, and the real
// gain over float32 was about one decade rather than the four a bad metric
// had suggested. See the README's precision section for the numbers.
//
// So this file carries the whole step in df. The float64 JS engine holds a
// proportional response down to a starting-position difference of ~1e-12,
// which is the target; float32 gives out around 1e-4.
//
// HOW TO READ IT
// --------------
// Every function here is a line-for-line port of its namesake in
// physics-gpu.js's GLSL_LIBRARY, which is itself a line-for-line port of
// physics-engine.js. Same formulas, same variable names, same order of
// operations - only the spelling changes, because GLSL cannot give a user
// type operators. `a + b` becomes `dfAdd(a, b)` for scalars and
// `dv2Add(a, b)` for vectors; `dot(a, b)` becomes `dv2Dot(a, b)`; a float
// literal `1.0` becomes `vec2(1.0, 0.0)`.
//
// That makes this a THIRD hand-synced implementation of the same physics,
// alongside physics-engine.js and the float32 GLSL. The project already
// accepts that trade for the first two (see the README's "Two
// implementations, kept in lockstep on purpose"), and the same defence
// applies here: physics-tests.js cross-checks this against both of them,
// and the grid's own precision override renders the float32 and df passes
// at the same view so they can be compared directly.
//
// THE ONE THING THAT IS NOT A STRAIGHT PORT
// -----------------------------------------
// df sin/cos is by far the most expensive routine in the library (a
// Cody-Waite reduction plus a Taylor series, where float32 has a hardware
// instruction). The float32 solver recomputes rotateVec(anchor, angle)
// inside every one of its 8 velocity iterations even though no velocity
// iteration touches an angle. Here the caller hoists that sin/cos out of
// the velocity loop and passes it in - exact, since the angle provably
// cannot change there. The POSITION loop does change angles, so it keeps
// recomputing per call, matching float32 exactly.
(function (global) {
  "use strict";

  var PhysicsDF = global.PhysicsDF;
  function d(n) { return PhysicsDF.num(n); }

  // Mirrors physics-gpu.js's own constants. Prefixed so a df shader can
  // include both libraries without colliding - the float32 one is still
  // pulled in for the per-pixel cascade's f32 helpers and for `Body`.
  var LINE_THICKNESS = 20;
  var LINE_PARALLEL_EPS = 0.05;
  var RESTITUTION_THRESHOLD = 30;
  var POSITION_SLOP = 0.01;
  var POSITION_PERCENT = 0.2;
  var FIXED_DT = 1 / 60;

  var GLSL = [
    "// ---- Double-float physics: a port of GLSL_LIBRARY in physics-gpu.js ----",
    "",
    "const vec2 DF_LINE_THICKNESS = " + d(LINE_THICKNESS) + ";",
    "const vec2 DF_LINE_PARALLEL_EPS = " + d(LINE_PARALLEL_EPS) + ";",
    "const vec2 DF_RESTITUTION_THRESHOLD = " + d(RESTITUTION_THRESHOLD) + ";",
    "const vec2 DF_POSITION_SLOP = " + d(POSITION_SLOP) + ";",
    "const vec2 DF_POSITION_PERCENT = " + d(POSITION_PERCENT) + ";",
    // 1/60 is not representable in binary at all, so unlike the float32
    // library's DT this literal actually carries the extra digits.
    "const vec2 DF_DT = " + d(FIXED_DT) + ";",
    "const vec2 DF_ZERO = vec2(0.0, 0.0);",
    "const vec2 DF_ONE = vec2(1.0, 0.0);",
    "const vec2 DF_EPS9 = " + d(1e-9) + ";",
    "const vec2 DF_EPS12 = " + d(1e-12) + ";",
    "const vec2 DF_EPS6 = " + d(1e-6) + ";",
    "",
    "bool dfIsZero(vec2 a) { return a.x == 0.0 && a.y == 0.0; }",
    "",
    "// The six per-body fields that carry a fine distinction forward.",
    "struct DBody { vec2 x; vec2 y; vec2 angle; vec2 vx; vec2 vy; vec2 w; };",
    "",
    "// .point is carried for fidelity with the float32 Contact even though",
    "// nothing downstream reads it - both solvers work from .normal, .rA,",
    "// .rB and .penetration. Keeping it means this struct can be compared",
    "// field-for-field against the float32 one when the two disagree.",
    "struct DContact { bool hit; DVec2 normal; DVec2 point; DVec2 rA; DVec2 rB; vec2 penetration; vec2 tHit; };",
    "struct DContactPair { DContact c0; DContact c1; };",
    "struct DClosestPair { DVec2 c1; DVec2 c2; };",
    "",
    "DContact dfNoContact() {",
    "  DContact c;",
    "  c.hit = false; c.normal = dv2Zero(); c.point = dv2Zero(); c.rA = dv2Zero(); c.rB = dv2Zero();",
    "  c.penetration = DF_ZERO; c.tHit = DF_ZERO;",
    "  return c;",
    "}",
    "",
    "// Both endpoints from one sin/cos. The float32 version calls",
    "// lineEndpoint0 and lineEndpoint1 separately, each doing its own",
    "// cos+sin; at df prices that would be four series evaluations where one",
    "// does.",
    "void dfLineEndpoints(DBody line, vec2 halfLen, out DVec2 e0, out DVec2 e1) {",
    "  vec2 sn, cs;",
    "  dfSinCos(line.angle, sn, cs);",
    "  vec2 dx = dfMul(cs, halfLen), dy = dfMul(sn, halfLen);",
    "  e0 = dv2(dfSub(line.x, dx), dfSub(line.y, dy));",
    "  e1 = dv2(dfAdd(line.x, dx), dfAdd(line.y, dy));",
    "}",
    "",
    "DVec2 dfClosestPointOnSegment(DVec2 p1, DVec2 p2, DVec2 point) {",
    "  DVec2 seg = dv2Sub(p2, p1);",
    "  vec2 lenSq = dv2Dot(seg, seg);",
    "  vec2 t = dfGreater(lenSq, DF_EPS12) ? dfDiv(dv2Dot(dv2Sub(point, p1), seg), lenSq) : DF_ZERO;",
    "  t = dfClamp(t, DF_ZERO, DF_ONE);",
    "  return dv2Add(p1, dv2Scale(seg, t));",
    "}",
    "",
    "DClosestPair dfClosestPointsSegmentSegment(DVec2 p1, DVec2 q1, DVec2 p2, DVec2 q2) {",
    "  DVec2 d1 = dv2Sub(q1, p1);",
    "  DVec2 d2 = dv2Sub(q2, p2);",
    "  DVec2 r = dv2Sub(p1, p2);",
    "  vec2 a = dv2Dot(d1, d1), e = dv2Dot(d2, d2), f = dv2Dot(d2, r);",
    "  vec2 s, t;",
    "  if (!dfGreater(a, DF_EPS9) && !dfGreater(e, DF_EPS9)) {",
    "    s = DF_ZERO; t = DF_ZERO;",
    "  } else if (!dfGreater(a, DF_EPS9)) {",
    "    s = DF_ZERO; t = dfClamp(dfDiv(f, e), DF_ZERO, DF_ONE);",
    "  } else {",
    "    vec2 c = dv2Dot(d1, r);",
    "    if (!dfGreater(e, DF_EPS9)) {",
    "      t = DF_ZERO; s = dfClamp(dfDiv(dfNeg(c), a), DF_ZERO, DF_ONE);",
    "    } else {",
    "      vec2 b = dv2Dot(d1, d2);",
    "      vec2 denom = dfSub(dfMul(a, e), dfMul(b, b));",
    "      s = !dfIsZero(denom) ? dfClamp(dfDiv(dfSub(dfMul(b, f), dfMul(c, e)), denom), DF_ZERO, DF_ONE) : DF_ZERO;",
    "      t = dfDiv(dfAdd(dfMul(b, s), f), e);",
    "      if (dfLess(t, DF_ZERO)) { t = DF_ZERO; s = dfClamp(dfDiv(dfNeg(c), a), DF_ZERO, DF_ONE); }",
    "      else if (dfGreater(t, DF_ONE)) { t = DF_ONE; s = dfClamp(dfDiv(dfSub(b, c), a), DF_ZERO, DF_ONE); }",
    "    }",
    "  }",
    "  DClosestPair result;",
    "  result.c1 = dv2Add(p1, dv2Scale(d1, s));",
    "  result.c2 = dv2Add(p2, dv2Scale(d2, t));",
    "  return result;",
    "}",
    "",
    "// Sweep primitives: earliest t in [0, dt] at which a point travelling",
    "// from p at velocity v first reaches distance R from the feature, or a",
    "// negative sentinel if that never happens inside the step.",
    "vec2 dfSweepPointSphere(DVec2 p, DVec2 v, DVec2 c, vec2 R, vec2 dt) {",
    "  DVec2 dvec = dv2Sub(p, c);",
    "  vec2 qc = dfSub(dv2Dot(dvec, dvec), dfMul(R, R));",
    "  if (!dfGreater(qc, DF_ZERO)) return DF_ZERO;",
    "  vec2 qa = dv2Dot(v, v);",
    "  if (!dfGreater(qa, DF_EPS9)) return dfNeg(DF_ONE);",
    "  vec2 qb = dfMulFloat(dv2Dot(dvec, v), 2.0);",
    "  vec2 disc = dfSub(dfMul(qb, qb), dfMulFloat(dfMul(qa, qc), 4.0));",
    "  if (dfLess(disc, DF_ZERO)) return dfNeg(DF_ONE);",
    "  vec2 t = dfDiv(dfSub(dfNeg(qb), dfSqrt(disc)), dfMulFloat(qa, 2.0));",
    "  if (dfLess(t, DF_ZERO) || dfGreater(t, dt)) return dfNeg(DF_ONE);",
    "  return t;",
    "}",
    "",
    "vec2 dfSweepPointSlab(DVec2 p, DVec2 v, DVec2 e0, DVec2 dir, vec2 len, vec2 R, vec2 dt) {",
    "  DVec2 perp = dv2Perp(dir);",
    "  vec2 f0 = dv2Dot(dv2Sub(p, e0), perp);",
    "  vec2 fv = dv2Dot(v, perp);",
    "  vec2 t;",
    "  if (!dfGreater(dfAbs(f0), R)) {",
    "    t = DF_ZERO;",
    "  } else {",
    "    vec2 target = dfGreater(f0, DF_ZERO) ? R : dfNeg(R);",
    "    if (!dfGreater(dfAbs(fv), DF_EPS9)) return dfNeg(DF_ONE);",
    "    t = dfDiv(dfSub(target, f0), fv);",
    "    if (dfLess(t, DF_ZERO) || dfGreater(t, dt)) return dfNeg(DF_ONE);",
    "  }",
    "  vec2 s = dv2Dot(dv2Sub(dv2Add(p, dv2Scale(v, t)), e0), dir);",
    "  if (dfLess(s, DF_ZERO) || dfGreater(s, len)) return dfNeg(DF_ONE);",
    "  return t;",
    "}",
    "",
    // accel is the body's whole acceleration (see advanceVelocity's own
    // comment in physics-gpu.js). It arrives as a DVec2 so that the uniform
    // case can keep passing the df gravity constant unchanged; under Mutual
    // Gravity it's a float32 result widened at the call site, which is the
    // same split used everywhere else here - precision lives in the
    // accumulators, not in the forces being accumulated.
    "DVec2 dfAdvanceVelocity(DVec2 v, vec2 dt, DVec2 accel) {",
    "  v.x = dfAdd(v.x, dfMul(accel.x, dt));",
    "  v.y = dfAdd(v.y, dfMul(accel.y, dt));",
    "  vec2 sq = dv2Dot(v, v);",
    "  if (dfGreater(sq, dfMul(DF_MAX_SPEED, DF_MAX_SPEED))) v = dv2Scale(v, dfDiv(DF_MAX_SPEED, dfSqrt(sq)));",
    "  return v;",
    "}",
    "",
    "DContact dfCollideCircleCircle(DBody a, vec2 ra, DBody b, vec2 rb) {",
    "  DVec2 dvec = dv2(dfSub(b.x, a.x), dfSub(b.y, a.y));",
    "  vec2 dist = dv2Length(dvec);",
    "  vec2 rsum = dfAdd(ra, rb);",
    "  DContact c = dfNoContact();",
    "  if (!dfLess(dist, rsum)) {",
    "    // Not touching at the start of the step - solve for whether",
    "    // straight-line motion brings them together before DT elapses. See",
    "    // the float32 collideCircleCircle for why this sub-step solve is",
    "    // what keeps the bounce a continuous function of the start.",
    "    DVec2 vRel = dv2(dfSub(b.vx, a.vx), dfSub(b.vy, a.vy));",
    "    vec2 qa = dv2Dot(vRel, vRel);",
    "    vec2 qb = dfMulFloat(dv2Dot(dvec, vRel), 2.0);",
    "    vec2 qc = dfSub(dv2Dot(dvec, dvec), dfMul(rsum, rsum));",
    "    vec2 disc = dfSub(dfMul(qb, qb), dfMulFloat(dfMul(qa, qc), 4.0));",
    "    if (!dfGreater(qa, DF_EPS9) || dfLess(disc, DF_ZERO)) return c;",
    "    vec2 t = dfDiv(dfSub(dfNeg(qb), dfSqrt(disc)), dfMulFloat(qa, 2.0));",
    "    if (dfLess(t, DF_ZERO) || dfGreater(t, DF_DT)) return c;",
    "    DVec2 hitD = dv2Add(dvec, dv2Scale(vRel, t));",
    "    vec2 hitDist = dv2Length(hitD);",
    "    DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "    if (dfGreater(hitDist, DF_EPS9)) n = dv2Scale(hitD, dfDiv(DF_ONE, hitDist));",
    "    DVec2 posA = dv2Add(dv2(a.x, a.y), dv2Scale(dv2(a.vx, a.vy), t));",
    "    c.hit = true;",
    "    c.normal = n;",
    "    c.point = dv2Add(posA, dv2Scale(n, ra));",
    "    c.rA = dv2Scale(n, ra);",
    "    c.rB = dv2Neg(dv2Scale(n, rb));",
    "    c.penetration = DF_ZERO;",
    "    c.tHit = t;",
    "    return c;",
    "  }",
    "  DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist, DF_EPS9)) n = dv2Scale(dvec, dfDiv(DF_ONE, dist));",
    "  c.hit = true;",
    "  c.normal = n;",
    "  c.point = dv2(dfAdd(a.x, dfMul(n.x, ra)), dfAdd(a.y, dfMul(n.y, ra)));",
    "  c.rA = dv2Scale(n, ra);",
    "  c.rB = dv2Neg(dv2Scale(n, rb));",
    "  c.penetration = dfSub(rsum, dist);",
    "  c.tHit = DF_ZERO;",
    "  return c;",
    "}",
    "",
    "DContact dfCollideLineCircle(DBody line, vec2 halfLen, DBody circle, vec2 radius) {",
    "  DVec2 e0, e1;",
    "  dfLineEndpoints(line, halfLen, e0, e1);",
    "  DVec2 p0 = dv2(circle.x, circle.y);",
    "  DVec2 vRel = dv2(dfSub(circle.vx, line.vx), dfSub(circle.vy, line.vy));",
    "  vec2 rsum = dfAdd(dfMulFloat(DF_LINE_THICKNESS, 0.5), radius);",
    "  DContact c = dfNoContact();",
    "",
    "  vec2 dist0 = dv2Length(dv2Sub(p0, dfClosestPointOnSegment(e0, e1, p0)));",
    "  vec2 tHit = DF_ZERO;",
    "",
    "  if (!dfLess(dist0, rsum)) {",
    "    DVec2 seg = dv2Sub(e1, e0);",
    "    vec2 segLen = dv2Length(seg);",
    "    DVec2 dir = dv2(DF_ONE, DF_ZERO);",
    "    if (dfGreater(segLen, DF_EPS9)) dir = dv2Scale(seg, dfDiv(DF_ONE, segLen));",
    "",
    "    vec2 best = dfNeg(DF_ONE);",
    "    vec2 tSlab = dfSweepPointSlab(p0, vRel, e0, dir, segLen, rsum, DF_DT);",
    "    if (!dfLess(tSlab, DF_ZERO)) best = tSlab;",
    "    vec2 tCap0 = dfSweepPointSphere(p0, vRel, e0, rsum, DF_DT);",
    "    if (!dfLess(tCap0, DF_ZERO) && (dfLess(best, DF_ZERO) || dfLess(tCap0, best))) best = tCap0;",
    "    vec2 tCap1 = dfSweepPointSphere(p0, vRel, e1, rsum, DF_DT);",
    "    if (!dfLess(tCap1, DF_ZERO) && (dfLess(best, DF_ZERO) || dfLess(tCap1, best))) best = tCap1;",
    "    if (dfLess(best, DF_ZERO)) return c;",
    "    tHit = best;",
    "  }",
    "",
    "  DVec2 pHit = dv2Add(p0, dv2Scale(vRel, tHit));",
    "  DVec2 closest = dfClosestPointOnSegment(e0, e1, pHit);",
    "  DVec2 dvec = dv2Sub(pHit, closest);",
    "  vec2 dist = dv2Length(dvec);",
    "  DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist, DF_EPS9)) n = dv2Scale(dvec, dfDiv(DF_ONE, dist));",
    "",
    "  DVec2 lineOffset = dv2Scale(dv2(line.vx, line.vy), tHit);",
    "  DVec2 pt = dv2Add(closest, dv2Scale(n, dfMulFloat(DF_LINE_THICKNESS, 0.5)));",
    "",
    "  c.hit = true;",
    "  c.normal = n;",
    "  c.point = dv2Add(pt, lineOffset);",
    "  c.rA = dv2Sub(pt, dv2(line.x, line.y));",
    "  c.rB = dv2Neg(dv2Scale(n, radius));",
    "  c.penetration = dfMax(dfSub(rsum, dist), DF_ZERO);",
    "  c.tHit = tHit;",
    "  return c;",
    "}",
    "",
    "DContactPair dfCollideLineLine(DBody lineA, vec2 halfLenA, DBody lineB, vec2 halfLenB) {",
    "  DVec2 eA0, eA1, eB0, eB1;",
    "  dfLineEndpoints(lineA, halfLenA, eA0, eA1);",
    "  dfLineEndpoints(lineB, halfLenB, eB0, eB1);",
    "",
    "  DContactPair result;",
    "  result.c0 = dfNoContact();",
    "  result.c1 = dfNoContact();",
    "",
    "  DVec2 dirA = dv2Sub(eA1, eA0);",
    "  vec2 lenA = dv2Length(dirA);",
    "  if (dfLess(lenA, DF_EPS9)) lenA = DF_ONE;",
    "  dirA = dv2Scale(dirA, dfDiv(DF_ONE, lenA));",
    "  DVec2 dirBraw = dv2Sub(eB1, eB0);",
    "  vec2 lenB = dv2Length(dirBraw);",
    "  if (dfLess(lenB, DF_EPS9)) lenB = DF_ONE;",
    "  DVec2 dirBn = dv2Scale(dirBraw, dfDiv(DF_ONE, lenB));",
    "  vec2 crossVal = dv2Cross(dirA, dirBn);",
    "",
    "  if (dfLess(dfAbs(crossVal), DF_LINE_PARALLEL_EPS)) {",
    "    DVec2 perp = dv2Perp(dirA);",
    "    vec2 offset = dv2Dot(dv2Sub(eB0, eA0), perp);",
    "    vec2 distP = dfAbs(offset);",
    "    if (dfLess(distP, DF_LINE_THICKNESS)) {",
    "      vec2 b0 = dv2Dot(dv2Sub(eB0, eA0), dirA);",
    "      vec2 b1 = dv2Dot(dv2Sub(eB1, eA0), dirA);",
    "      vec2 lo = dfMax(DF_ZERO, dfMin(b0, b1));",
    "      vec2 hi = dfMin(lenA, dfMax(b0, b1));",
    "      if (dfGreater(hi, lo)) {",
    "        vec2 sgn = !dfLess(offset, DF_ZERO) ? DF_ONE : dfNeg(DF_ONE);",
    "        DVec2 normal = dv2Scale(perp, sgn);",
    "        vec2 penetration = dfSub(DF_LINE_THICKNESS, distP);",
    "        DVec2 pOnA0 = dv2Add(eA0, dv2Scale(dirA, lo));",
    "        DVec2 pOnA1 = dv2Add(eA0, dv2Scale(dirA, hi));",
    "        DVec2 pt0 = dv2Add(pOnA0, dv2Scale(perp, dfMulFloat(offset, 0.5)));",
    "        result.c0.hit = true;",
    "        result.c0.normal = normal;",
    "        result.c0.point = pt0;",
    "        result.c0.rA = dv2Sub(pt0, dv2(lineA.x, lineA.y));",
    "        result.c0.rB = dv2Sub(pt0, dv2(lineB.x, lineB.y));",
    "        result.c0.penetration = penetration;",
    "        result.c0.tHit = DF_ZERO;",
    "        if (dfGreater(dfSub(hi, lo), DF_EPS6)) {",
    "          DVec2 pt1 = dv2Add(pOnA1, dv2Scale(perp, dfMulFloat(offset, 0.5)));",
    "          result.c1.hit = true;",
    "          result.c1.normal = normal;",
    "          result.c1.point = pt1;",
    "          result.c1.rA = dv2Sub(pt1, dv2(lineA.x, lineA.y));",
    "          result.c1.rB = dv2Sub(pt1, dv2(lineB.x, lineB.y));",
    "          result.c1.penetration = penetration;",
    "          result.c1.tHit = DF_ZERO;",
    "        }",
    "        return result;",
    "      }",
    "    }",
    "  }",
    "",
    "  DClosestPair cp = dfClosestPointsSegmentSegment(eA0, eA1, eB0, eB1);",
    "  DVec2 d2v = dv2Sub(cp.c2, cp.c1);",
    "  vec2 dist2 = dv2Length(d2v);",
    "  if (!dfLess(dist2, DF_LINE_THICKNESS)) return result;",
    "  DVec2 n2 = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist2, DF_EPS9)) n2 = dv2Scale(d2v, dfDiv(DF_ONE, dist2));",
    "  DVec2 pt2 = dv2Scale(dv2Add(cp.c1, cp.c2), " + d(0.5) + ");",
    "  result.c0.hit = true;",
    "  result.c0.normal = n2;",
    "  result.c0.point = pt2;",
    "  result.c0.rA = dv2Sub(pt2, dv2(lineA.x, lineA.y));",
    "  result.c0.rB = dv2Sub(pt2, dv2(lineB.x, lineB.y));",
    "  result.c0.penetration = dfSub(DF_LINE_THICKNESS, dist2);",
    "  result.c0.tHit = DF_ZERO;",
    "  return result;",
    "}",
    "",
    "void dfApplyImpulse(inout DBody b, vec2 invMass, vec2 invInertia, DVec2 impulse, DVec2 r) {",
    "  b.vx = dfAdd(b.vx, dfMul(impulse.x, invMass));",
    "  b.vy = dfAdd(b.vy, dfMul(impulse.y, invMass));",
    "  b.w = dfAdd(b.w, dfMul(invInertia, dv2Cross(r, impulse)));",
    "}",
    "",
    "DVec2 dfVelocityAt(DBody b, DVec2 r) {",
    "  return dv2(dfSub(b.vx, dfMul(b.w, r.y)), dfAdd(b.vy, dfMul(b.w, r.x)));",
    "}",
    "",
    "void dfSolveContactVelocity(inout DBody bodyA, vec2 invMassA, vec2 invInertiaA,",
    "                            inout DBody bodyB, vec2 invMassB, vec2 invInertiaB,",
    "                            DContact contact, vec2 friction, vec2 restitution) {",
    "  if (!contact.hit) return;",
    "  DVec2 n = contact.normal;",
    "  DVec2 rA = contact.rA;",
    "  DVec2 rB = contact.rB;",
    "",
    "  DVec2 vA = dfVelocityAt(bodyA, rA);",
    "  DVec2 vB = dfVelocityAt(bodyB, rB);",
    "  DVec2 rv = dv2Sub(vB, vA);",
    "  vec2 velAlongNormal = dv2Dot(rv, n);",
    "  if (dfGreater(velAlongNormal, DF_ZERO)) return;",
    "",
    "  vec2 raCrossN = dv2Cross(rA, n);",
    "  vec2 rbCrossN = dv2Cross(rB, n);",
    "  vec2 invMassSum = dfAdd(dfAdd(invMassA, invMassB),",
    "                     dfAdd(dfMul(dfMul(raCrossN, raCrossN), invInertiaA),",
    "                           dfMul(dfMul(rbCrossN, rbCrossN), invInertiaB)));",
    "  if (!dfGreater(invMassSum, DF_ZERO)) return;",
    "",
    "  vec2 e = dfMul(restitution, dfSmoothstep(dfMulFloat(DF_RESTITUTION_THRESHOLD, 0.5), DF_RESTITUTION_THRESHOLD, dfNeg(velAlongNormal)));",
    "  vec2 j = dfDiv(dfNeg(dfMul(dfAdd(DF_ONE, e), velAlongNormal)), invMassSum);",
    "  dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2(dfNeg(dfMul(n.x, j)), dfNeg(dfMul(n.y, j))), rA);",
    "  dfApplyImpulse(bodyB, invMassB, invInertiaB, dv2(dfMul(n.x, j), dfMul(n.y, j)), rB);",
    "",
    "  DVec2 vA2 = dfVelocityAt(bodyA, rA);",
    "  DVec2 vB2 = dfVelocityAt(bodyB, rB);",
    "  DVec2 rv2 = dv2Sub(vB2, vA2);",
    "  vec2 vAlongN2 = dv2Dot(rv2, n);",
    "  DVec2 tangent = dv2Sub(rv2, dv2Scale(n, vAlongN2));",
    "  vec2 tLen = dv2Length(tangent);",
    "  if (dfGreater(tLen, DF_EPS9)) {",
    "    tangent = dv2Scale(tangent, dfDiv(DF_ONE, tLen));",
    "    vec2 raCrossT = dv2Cross(rA, tangent);",
    "    vec2 rbCrossT = dv2Cross(rB, tangent);",
    "    vec2 invMassSumT = dfAdd(dfAdd(invMassA, invMassB),",
    "                        dfAdd(dfMul(dfMul(raCrossT, raCrossT), invInertiaA),",
    "                              dfMul(dfMul(rbCrossT, rbCrossT), invInertiaB)));",
    "    if (dfGreater(invMassSumT, DF_ZERO)) {",
    "      vec2 limit = dfMul(friction, dfAbs(j));",
    "      vec2 jt = dfClamp(dfDiv(dfNeg(dv2Dot(rv2, tangent)), invMassSumT), dfNeg(limit), limit);",
    "      dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2(dfNeg(dfMul(tangent.x, jt)), dfNeg(dfMul(tangent.y, jt))), rA);",
    "      dfApplyImpulse(bodyB, invMassB, invInertiaB, dv2(dfMul(tangent.x, jt), dfMul(tangent.y, jt)), rB);",
    "    }",
    "  }",
    "}",
    "",
    "void dfSolveContactPosition(inout DBody bodyA, vec2 invMassA, inout DBody bodyB, vec2 invMassB, DContact contact) {",
    "  if (!contact.hit) return;",
    "  vec2 invMassSum = dfAdd(invMassA, invMassB);",
    "  if (!dfGreater(invMassSum, DF_ZERO)) return;",
    "  vec2 correction = dfMul(dfDiv(dfMax(dfSub(contact.penetration, DF_POSITION_SLOP), DF_ZERO), invMassSum), DF_POSITION_PERCENT);",
    "  DVec2 n = contact.normal;",
    "  bodyA.x = dfSub(bodyA.x, dfMul(dfMul(n.x, correction), invMassA));",
    "  bodyA.y = dfSub(bodyA.y, dfMul(dfMul(n.y, correction), invMassA));",
    "  bodyB.x = dfAdd(bodyB.x, dfMul(dfMul(n.x, correction), invMassB));",
    "  bodyB.y = dfAdd(bodyB.y, dfMul(dfMul(n.y, correction), invMassB));",
    "}",
    "",
    "DVec2 dfSolve2x2(vec2 mA, vec2 iA, DVec2 rA, vec2 mB, vec2 iB, DVec2 rB, vec2 rhsX, vec2 rhsY) {",
    "  if (!dfGreater(dfAdd(dfAdd(mA, mB), dfAdd(iA, iB)), DF_ZERO)) return dv2Zero();",
    "  vec2 k11 = dfAdd(dfAdd(mA, mB), dfAdd(dfMul(iA, dfMul(rA.y, rA.y)), dfMul(iB, dfMul(rB.y, rB.y))));",
    "  vec2 k12 = dfSub(dfNeg(dfMul(iA, dfMul(rA.x, rA.y))), dfMul(iB, dfMul(rB.x, rB.y)));",
    "  vec2 k22 = dfAdd(dfAdd(mA, mB), dfAdd(dfMul(iA, dfMul(rA.x, rA.x)), dfMul(iB, dfMul(rB.x, rB.x))));",
    "  vec2 det = dfSub(dfMul(k11, k22), dfMul(k12, k12));",
    "  vec2 invDet = dfDiv(DF_ONE, det);",
    "  return dv2(dfMul(invDet, dfSub(dfMul(k22, rhsX), dfMul(k12, rhsY))),",
    "             dfMul(invDet, dfSub(dfMul(k11, rhsY), dfMul(k12, rhsX))));",
    "}",
    "",
    "// snA/csA and snB/csB are each body's sin/cos, supplied by the caller.",
    "// No velocity iteration touches an angle, so the step loop computes",
    "// these once and reuses them across all 8 - exact, and it is the single",
    "// biggest saving available in this file.",
    "void dfSolveHingeVelocity(inout DBody bodyA, vec2 invMassA, vec2 invInertiaA, DVec2 localAnchorA, vec2 snA, vec2 csA,",
    "                          inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, DVec2 localAnchorB, vec2 snB, vec2 csB) {",
    "  DVec2 rA = dv2RotateBy(localAnchorA, snA, csA);",
    "  DVec2 rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  DVec2 vA = dfVelocityAt(bodyA, rA);",
    "  DVec2 vB = dfVelocityAt(bodyB, rB);",
    "  DVec2 cdot = dv2Sub(vB, vA);",
    "  DVec2 impulse = dfSolve2x2(invMassA, invInertiaA, rA, invMassB, invInertiaB, rB, dfNeg(cdot.x), dfNeg(cdot.y));",
    "  dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2Neg(impulse), rA);",
    "  dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, rB);",
    "}",
    "",
    "// Recomputes its own sin/cos, unlike the velocity solver above: the",
    "// position solve DOES rotate bodies, so a hoisted value would go stale",
    "// mid-iteration and stop matching the float32 path.",
    "void dfSolveHingePosition(inout DBody bodyA, vec2 invMassA, vec2 invInertiaA, DVec2 localAnchorA,",
    "                          inout DBody bodyB, vec2 invMassB, vec2 invInertiaB, DVec2 localAnchorB) {",
    "  vec2 snA, csA, snB, csB;",
    "  dfSinCos(bodyA.angle, snA, csA);",
    "  dfSinCos(bodyB.angle, snB, csB);",
    "  DVec2 rA = dv2RotateBy(localAnchorA, snA, csA);",
    "  DVec2 rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  DVec2 worldA = dv2Add(dv2(bodyA.x, bodyA.y), rA);",
    "  DVec2 worldB = dv2Add(dv2(bodyB.x, bodyB.y), rB);",
    "  DVec2 c = dv2Sub(worldB, worldA);",
    "  DVec2 impulse = dfSolve2x2(invMassA, invInertiaA, rA, invMassB, invInertiaB, rB, dfNeg(c.x), dfNeg(c.y));",
    "  bodyA.x = dfSub(bodyA.x, dfMul(impulse.x, invMassA));",
    "  bodyA.y = dfSub(bodyA.y, dfMul(impulse.y, invMassA));",
    "  bodyA.angle = dfSub(bodyA.angle, dfMul(invInertiaA, dv2Cross(rA, impulse)));",
    "  bodyB.x = dfAdd(bodyB.x, dfMul(impulse.x, invMassB));",
    "  bodyB.y = dfAdd(bodyB.y, dfMul(impulse.y, invMassB));",
    "  bodyB.angle = dfAdd(bodyB.angle, dfMul(invInertiaB, dv2Cross(rB, impulse)));",
    "}",
  ].join("\n");

  global.PhysicsGPUDF = { GLSL_LIBRARY: GLSL };
})(typeof window !== "undefined" ? window : globalThis);
