// CPAL-1.0 License. See chaosaccelerator.com/license.html

// Multi-float port of physics-gpu.js's GLSL_LIBRARY: same formulas and names,
// operators spelled as dfAdd/dv2Add calls, MF as the scalar type (vec2/3/4 per
// physics-df.js). Not line-for-line: segment geometry, hinge and contact prep
// are hoisted out of the loops, and the position solve nudges its sin/cos.
(function (global) {
  "use strict";

  var PhysicsDF = global.PhysicsDF;
  function d(n) { return PhysicsDF.num(n); }

  // physics-gpu.js's constants, prefixed so a df shader can include both libraries.
  var LINE_THICKNESS = 20;
  var LINE_PARALLEL_EPS = 0.05;
  var RESTITUTION_THRESHOLD = 30;
  var POSITION_SLOP = 0.01;
  var POSITION_PERCENT = 0.2;
  var FIXED_DT = 1 / 60;

  // Read at shader generation, so a measurement page can flip one and rebuild.
  // nudgeTrig off makes this bit-identical to a straight port (physics-tests.js uses that).
  var OPTIONS = { nudgeTrig: true };

  function buildLibrary() {
    return [
    "// ---- Multi-float physics: a port of GLSL_LIBRARY in physics-gpu.js ----",
    "",
    "const MF DF_LINE_THICKNESS = " + d(LINE_THICKNESS) + ";",
    "const MF DF_HALF_LINE_THICKNESS = " + d(LINE_THICKNESS * 0.5) + ";",
    "const MF DF_LINE_PARALLEL_EPS = " + d(LINE_PARALLEL_EPS) + ";",
    "const MF DF_RESTITUTION_THRESHOLD = " + d(RESTITUTION_THRESHOLD) + ";",
    "const MF DF_HALF_RESTITUTION_THRESHOLD = " + d(RESTITUTION_THRESHOLD * 0.5) + ";",
    "const MF DF_POSITION_SLOP = " + d(POSITION_SLOP) + ";",
    "const MF DF_POSITION_PERCENT = " + d(POSITION_PERCENT) + ";",
    // 1/60 is inexact in binary, so unlike the float32 DT this carries extra digits.
    "const MF DF_DT = " + d(FIXED_DT) + ";",
    "const MF DF_GRAVITY = " + d(global.PhysicsEngine.GRAVITY) + ";",
    "const MF DF_ZERO = MF(0.0);",
    "const MF DF_ONE = DF_ONE_CONST;",
    "const MF DF_EPS9 = " + d(1e-9) + ";",
    "const MF DF_EPS12 = " + d(1e-12) + ";",
    "const MF DF_EPS6 = " + d(1e-6) + ";",
    "",
    "bool dfIsZero(MF a) { return all(equal(a, MF(0.0))); }",
    "",
    "// The six per-body fields that carry a fine distinction forward.",
    "struct DBody { MF x; MF y; MF angle; MF vx; MF vy; MF w; };",
    "",
    "// .point is carried for fidelity with the float32 Contact even though",
    "// nothing downstream reads it: both solvers work from .normal, .rA,",
    "// .rB and .penetration. Keeping it means this struct can be compared",
    "// field-for-field against the float32 one when the two disagree.",
    "// invMassSum/pushA/pushB are dfPrepareContact's: what the two solvers",
    "// would otherwise re-derive, identically, on every iteration.",
    "struct DContact { bool hit; DVec2 normal; DVec2 point; DVec2 rA; DVec2 rB; MF penetration; MF tHit;",
    "                  MF invMassSum; DVec2 pushA; DVec2 pushB; };",
    "struct DContactPair { DContact c0; DContact c1; };",
    "struct DClosestPair { DVec2 c1; DVec2 c2; };",
    "",
    "DContact dfNoContact() {",
    "  DContact c;",
    "  c.hit = false; c.normal = dv2Zero(); c.point = dv2Zero(); c.rA = dv2Zero(); c.rB = dv2Zero();",
    "  c.penetration = DF_ZERO; c.tHit = DF_ZERO;",
    "  c.invMassSum = DF_ZERO; c.pushA = dv2Zero(); c.pushB = dv2Zero();",
    "  return c;",
    "}",
    "",
    "// ---- Segments ----",
    "//",
    "// Everything the collision tests ever ask of a segment, built once: see",
    "// this file's header. physics-gpu.js's generated step decides how often",
    "// 'once' is: per step for anything that can move, per run for anything",
    "// anchored. g_dfStaticGeomReady is the flag that second case runs on; it",
    "// lives here rather than in the generated code so that every df shader",
    "// has it, including ones that declare bodies without ever stepping them.",
    "struct DSegment { DVec2 e0; DVec2 e1; DVec2 seg; MF lenSq; MF len; DVec2 dir; };",
    "bool g_dfStaticGeomReady = false;",
    "",
    "DSegment dfSegment(DVec2 e0, DVec2 e1) {",
    "  DSegment g;",
    "  g.e0 = e0; g.e1 = e1;",
    "  g.seg = dv2Sub(e1, e0);",
    "  g.lenSq = dv2LengthSq(g.seg);",
    "  g.len = dfSqrt(g.lenSq);",
    "  g.dir = dv2(DF_ONE, DF_ZERO);",
    "  if (dfGreater(g.len, DF_EPS9)) g.dir = dv2Scale(g.seg, dfDiv(DF_ONE, g.len));",
    "  return g;",
    "}",
    "",
    "// Both endpoints from one sin/cos. The float32 version calls",
    "// lineEndpoint0 and lineEndpoint1 separately, each doing its own",
    "// cos+sin; at df prices that would be four series evaluations where one",
    "// does.",
    "void dfLineEndpoints(DBody line, MF halfLen, out DVec2 e0, out DVec2 e1) {",
    "  MF sn, cs;",
    "  dfSinCos(line.angle, sn, cs);",
    "  MF dx = dfMul(cs, halfLen), dy = dfMul(sn, halfLen);",
    "  e0 = dv2(dfSub(line.x, dx), dfSub(line.y, dy));",
    "  e1 = dv2(dfAdd(line.x, dx), dfAdd(line.y, dy));",
    "}",
    "",
    "DSegment dfLineSegment(DBody line, MF halfLen) {",
    "  DVec2 e0, e1;",
    "  dfLineEndpoints(line, halfLen, e0, e1);",
    "  return dfSegment(e0, e1);",
    "}",
    "",
    "DVec2 dfClosestPointOnSegment(DSegment g, DVec2 point) {",
    "  MF t = dfGreater(g.lenSq, DF_EPS12) ? dfDiv(dv2Dot(dv2Sub(point, g.e0), g.seg), g.lenSq) : DF_ZERO;",
    "  t = dfClamp(t, DF_ZERO, DF_ONE);",
    "  return dv2Add(g.e0, dv2Scale(g.seg, t));",
    "}",
    "",
    "DClosestPair dfClosestPointsSegmentSegment(DSegment g1, DSegment g2) {",
    "  DVec2 p1 = g1.e0, p2 = g2.e0;",
    "  DVec2 d1 = g1.seg;",
    "  DVec2 d2 = g2.seg;",
    "  DVec2 r = dv2Sub(p1, p2);",
    "  MF a = g1.lenSq, e = g2.lenSq, f = dv2Dot(d2, r);",
    "  MF s, t;",
    "  if (!dfGreater(a, DF_EPS9) && !dfGreater(e, DF_EPS9)) {",
    "    s = DF_ZERO; t = DF_ZERO;",
    "  } else if (!dfGreater(a, DF_EPS9)) {",
    "    s = DF_ZERO; t = dfClamp(dfDiv(f, e), DF_ZERO, DF_ONE);",
    "  } else {",
    "    MF c = dv2Dot(d1, r);",
    "    if (!dfGreater(e, DF_EPS9)) {",
    "      t = DF_ZERO; s = dfClamp(dfDiv(dfNeg(c), a), DF_ZERO, DF_ONE);",
    "    } else {",
    "      MF b = dv2Dot(d1, d2);",
    "      MF denom = dfSub(dfMul(a, e), dfSqr(b));",
    "      s = !dfIsZero(denom) ? dfClamp(dfDiv(dfSub(dfMul(b, f), dfMul(c, e)), denom), DF_ZERO, DF_ONE) : DF_ZERO;",
    "      t = dfDiv(dfAdd(dfMul(b, s), f), e);",
    "      if (dfLess(t, DF_ZERO)) { t = DF_ZERO; s = dfClamp(dfDiv(dfNeg(c), a), DF_ZERO, DF_ONE); }",
    "      else if (dfGreater(t, DF_ONE)) { t = DF_ONE; s = dfClamp(dfDiv(dfSub(b, c), a), DF_ZERO, DF_ONE); }",
    "    }",
    "  }",
    "  DClosestPair result;",
    "  result.c1 = dv2Add(p1, dv2Scale(d1, s));",
    "  result.c2 = dv2Add(p2, dv2Scale(d2, t));",
    "  return result;",
    "}",
    "",
    "// Sweep primitives: earliest t in [0, dt] at which a point travelling",
    "// from p at velocity v first reaches distance R from the feature, or a",
    "// negative sentinel if that never happens inside the step.",
    "MF dfSweepPointSphere(DVec2 p, DVec2 v, DVec2 c, MF R, MF dt) {",
    "  DVec2 dvec = dv2Sub(p, c);",
    "  MF qc = dfSub(dv2LengthSq(dvec), dfSqr(R));",
    "  if (!dfGreater(qc, DF_ZERO)) return DF_ZERO;",
    "  MF qa = dv2LengthSq(v);",
    "  if (!dfGreater(qa, DF_EPS9)) return dfNeg(DF_ONE);",
    "  MF qb = dfMulPow2(dv2Dot(dvec, v), 2.0);",
    "  MF disc = dfSub(dfSqr(qb), dfMulPow2(dfMul(qa, qc), 4.0));",
    "  if (dfLess(disc, DF_ZERO)) return dfNeg(DF_ONE);",
    "  MF t = dfDiv(dfSub(dfNeg(qb), dfSqrt(disc)), dfMulPow2(qa, 2.0));",
    "  if (dfLess(t, DF_ZERO) || dfGreater(t, dt)) return dfNeg(DF_ONE);",
    "  return t;",
    "}",
    "",
    "MF dfSweepPointSlab(DVec2 p, DVec2 v, DVec2 e0, DVec2 dir, MF len, MF R, MF dt) {",
    "  DVec2 perp = dv2Perp(dir);",
    "  MF f0 = dv2Dot(dv2Sub(p, e0), perp);",
    "  MF fv = dv2Dot(v, perp);",
    "  MF t;",
    "  if (!dfGreater(dfAbs(f0), R)) {",
    "    t = DF_ZERO;",
    "  } else {",
    "    MF target = dfGreater(f0, DF_ZERO) ? R : dfNeg(R);",
    "    if (!dfGreater(dfAbs(fv), DF_EPS9)) return dfNeg(DF_ONE);",
    "    t = dfDiv(dfSub(target, f0), fv);",
    "    if (dfLess(t, DF_ZERO) || dfGreater(t, dt)) return dfNeg(DF_ONE);",
    "  }",
    "  MF s = dv2Dot(dv2Sub(dv2Add(p, dv2Scale(v, t)), e0), dir);",
    "  if (dfLess(s, DF_ZERO) || dfGreater(s, len)) return dfNeg(DF_ONE);",
    "  return t;",
    "}",
    "",
    "DVec2 dfDragAndCap(DVec2 v, MF dt) {",
    // PhysicsEngine.AIR_DRAG (experimental): no line at all when it is 0.
    (global.PhysicsEngine.AIR_DRAG ? "  v = dv2Scale(v, dfSub(DF_ONE, dfMul(" + d(global.PhysicsEngine.AIR_DRAG) + ", dt)));" : ""),
    "  MF sq = dv2LengthSq(v);",
    "  if (dfGreater(sq, dfSqr(DF_MAX_SPEED))) v = dv2Scale(v, dfDiv(DF_MAX_SPEED, dfSqrt(sq)));",
    "  return v;",
    "}",
    // accel is the body's whole acceleration: a spring sum, or under Mutual
    // Gravity the df force sum the generated step builds.
    "DVec2 dfAdvanceVelocity(DVec2 v, MF dt, DVec2 accel) {",
    "  v.x = dfAdd(v.x, dfMul(accel.x, dt));",
    "  v.y = dfAdd(v.y, dfMul(accel.y, dt));",
    "  return dfDragAndCap(v, dt);",
    "}",
    // Plain gravity: its x component is zero, and a df multiply-add of zero is
    // real work behind the dfv() veil.
    "DVec2 dfAdvanceVelocityGravity(DVec2 v, MF dt) {",
    "  v.y = dfAdd(v.y, dfMul(DF_GRAVITY, dt));",
    "  return dfDragAndCap(v, dt);",
    "}",
    "",
    "DContact dfCollideCircleCircle(DBody a, MF ra, DBody b, MF rb) {",
    "  DVec2 dvec = dv2(dfSub(b.x, a.x), dfSub(b.y, a.y));",
    "  MF distSq = dv2LengthSq(dvec);",
    "  MF dist = dfSqrt(distSq);",
    "  MF rsum = dfAdd(ra, rb);",
    "  DContact c = dfNoContact();",
    "  if (!dfLess(dist, rsum)) {",
    "    // Not touching at the start of the step: solve for whether",
    "    // straight-line motion brings them together before DT elapses. See",
    "    // the float32 collideCircleCircle for why this sub-step solve is",
    "    // what keeps the bounce a continuous function of the start.",
    "    DVec2 vRel = dv2(dfSub(b.vx, a.vx), dfSub(b.vy, a.vy));",
    "    MF qa = dv2LengthSq(vRel);",
    "    MF qb = dfMulPow2(dv2Dot(dvec, vRel), 2.0);",
    "    MF qc = dfSub(distSq, dfSqr(rsum));",
    "    MF disc = dfSub(dfSqr(qb), dfMulPow2(dfMul(qa, qc), 4.0));",
    "    if (!dfGreater(qa, DF_EPS9) || dfLess(disc, DF_ZERO)) return c;",
    "    MF t = dfDiv(dfSub(dfNeg(qb), dfSqrt(disc)), dfMulPow2(qa, 2.0));",
    "    if (dfLess(t, DF_ZERO) || dfGreater(t, DF_DT)) return c;",
    "    DVec2 hitD = dv2Add(dvec, dv2Scale(vRel, t));",
    "    MF hitDist = dv2Length(hitD);",
    "    DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "    if (dfGreater(hitDist, DF_EPS9)) n = dv2Scale(hitD, dfDiv(DF_ONE, hitDist));",
    "    DVec2 posA = dv2Add(dv2(a.x, a.y), dv2Scale(dv2(a.vx, a.vy), t));",
    "    c.hit = true;",
    "    c.normal = n;",
    "    c.point = dv2Add(posA, dv2Scale(n, ra));",
    "    c.rA = dv2Scale(n, ra);",
    "    c.rB = dv2Neg(dv2Scale(n, rb));",
    "    c.penetration = DF_ZERO;",
    "    c.tHit = t;",
    "    return c;",
    "  }",
    "  DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist, DF_EPS9)) n = dv2Scale(dvec, dfDiv(DF_ONE, dist));",
    "  c.hit = true;",
    "  c.normal = n;",
    "  c.point = dv2(dfAdd(a.x, dfMul(n.x, ra)), dfAdd(a.y, dfMul(n.y, ra)));",
    "  c.rA = dv2Scale(n, ra);",
    "  c.rB = dv2Neg(dv2Scale(n, rb));",
    "  c.penetration = dfSub(rsum, dist);",
    "  c.tHit = DF_ZERO;",
    "  return c;",
    "}",
    "",
    "// Swept capsule (segment g, half-thickness halfThickness, moving at",
    "// constant velocity segVel, otherwise rigid) vs. circle: the port of",
    "// sweptCapsuleCircleContact. refCenter is the line's center, since rA",
    "// is a lever arm on its body.",
    // vRel is the circle's velocity in the segment's frame; .point is left in that frame.
    "DContact dfSweptCapsuleCircleContactRel(DSegment g, DVec2 vRel, DVec2 refCenter, DBody circle, MF radius, MF halfThickness) {",
    "  DVec2 p0 = dv2(circle.x, circle.y);",
    "  MF rsum = dfAdd(halfThickness, radius);",
    "  DContact c = dfNoContact();",
    "",
    "  MF dist0 = dv2Length(dv2Sub(p0, dfClosestPointOnSegment(g, p0)));",
    "  MF tHit = DF_ZERO;",
    "",
    "  if (!dfLess(dist0, rsum)) {",
    "    MF best = dfNeg(DF_ONE);",
    "    MF tSlab = dfSweepPointSlab(p0, vRel, g.e0, g.dir, g.len, rsum, DF_DT);",
    "    if (!dfLess(tSlab, DF_ZERO)) best = tSlab;",
    "    MF tCap0 = dfSweepPointSphere(p0, vRel, g.e0, rsum, DF_DT);",
    "    if (!dfLess(tCap0, DF_ZERO) && (dfLess(best, DF_ZERO) || dfLess(tCap0, best))) best = tCap0;",
    "    MF tCap1 = dfSweepPointSphere(p0, vRel, g.e1, rsum, DF_DT);",
    "    if (!dfLess(tCap1, DF_ZERO) && (dfLess(best, DF_ZERO) || dfLess(tCap1, best))) best = tCap1;",
    "    if (dfLess(best, DF_ZERO)) return c;",
    "    tHit = best;",
    "  }",
    "",
    "  DVec2 pHit = dv2Add(p0, dv2Scale(vRel, tHit));",
    "  DVec2 closest = dfClosestPointOnSegment(g, pHit);",
    "  DVec2 dvec = dv2Sub(pHit, closest);",
    "  MF dist = dv2Length(dvec);",
    "  DVec2 n = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist, DF_EPS9)) n = dv2Scale(dvec, dfDiv(DF_ONE, dist));",
    "",
    "  DVec2 pt = dv2Add(closest, dv2Scale(n, halfThickness));",
    "",
    "  c.hit = true;",
    "  c.normal = n;",
    "  c.point = pt;",
    "  c.rA = dv2Sub(pt, refCenter);",
    "  c.rB = dv2Neg(dv2Scale(n, radius));",
    "  c.penetration = dfMax(dfSub(rsum, dist), DF_ZERO);",
    "  c.tHit = tHit;",
    "  return c;",
    "}",
    "",
    "// The segment's own translation over tHit shifts .point and its reference",
    "// center equally, so it cancels out of rA.",
    "DContact dfSweptCapsuleCircleContact(DSegment g, DVec2 segVel, DVec2 refCenter, DBody circle, MF radius, MF halfThickness) {",
    "  DContact c = dfSweptCapsuleCircleContactRel(g, dv2Sub(dv2(circle.vx, circle.vy), segVel), refCenter, circle, radius, halfThickness);",
    "  if (c.hit) c.point = dv2Add(c.point, dv2Scale(segVel, c.tHit));",
    "  return c;",
    "}",
    "",
    "// An anchored segment: its velocity is a known zero, so nothing to subtract or shift.",
    "DContact dfSweptCapsuleCircleContactStatic(DSegment g, DVec2 refCenter, DBody circle, MF radius, MF halfThickness) {",
    "  return dfSweptCapsuleCircleContactRel(g, dv2(circle.vx, circle.vy), refCenter, circle, radius, halfThickness);",
    "}",
    "",
    "// line -> circle; normal points line -> circle. g is the line's own",
    "// segment, built by whoever calls this (see the header).",
    "DContact dfCollideLineCircle(DBody line, DSegment g, DBody circle, MF radius) {",
    "  return dfSweptCapsuleCircleContact(g, dv2(line.vx, line.vy), dv2(line.x, line.y), circle, radius, DF_HALF_LINE_THICKNESS);",
    "}",
    "DContact dfCollideLineCircleStatic(DBody line, DSegment g, DBody circle, MF radius) {",
    "  return dfSweptCapsuleCircleContactStatic(g, dv2(line.x, line.y), circle, radius, DF_HALF_LINE_THICKNESS);",
    "}",
    "",
    "DContactPair dfCollideLineLine(DBody lineA, DSegment gA, DBody lineB, DSegment gB) {",
    "  DVec2 eA0 = gA.e0, eB0 = gB.e0, eB1 = gB.e1;",
    "",
    "  DContactPair result;",
    "  result.c0 = dfNoContact();",
    "  result.c1 = dfNoContact();",
    "",
    "  // The float32 version normalizes by a length it first bumps to 1.0 when",
    "  // degenerate; a DSegment's own dir falls back to (1, 0) instead, which",
    "  // is what the capsule test wants. Put this function's convention back",
    "  // for the two cases where they differ.",
    "  DVec2 dirA = gA.dir;",
    "  MF lenA = gA.len;",
    "  if (dfLess(lenA, DF_EPS9)) { lenA = DF_ONE; dirA = gA.seg; }",
    "  else if (!dfGreater(lenA, DF_EPS9)) dirA = dv2Scale(gA.seg, dfDiv(DF_ONE, lenA));",
    "  DVec2 dirBn = gB.dir;",
    "  if (dfLess(gB.len, DF_EPS9)) dirBn = gB.seg;",
    "  else if (!dfGreater(gB.len, DF_EPS9)) dirBn = dv2Scale(gB.seg, dfDiv(DF_ONE, gB.len));",
    "  MF crossVal = dv2Cross(dirA, dirBn);",
    "",
    "  if (dfLess(dfAbs(crossVal), DF_LINE_PARALLEL_EPS)) {",
    "    DVec2 perp = dv2Perp(dirA);",
    "    MF offset = dv2Dot(dv2Sub(eB0, eA0), perp);",
    "    MF distP = dfAbs(offset);",
    "    if (dfLess(distP, DF_LINE_THICKNESS)) {",
    "      MF b0 = dv2Dot(dv2Sub(eB0, eA0), dirA);",
    "      MF b1 = dv2Dot(dv2Sub(eB1, eA0), dirA);",
    "      MF lo = dfMax(DF_ZERO, dfMin(b0, b1));",
    "      MF hi = dfMin(lenA, dfMax(b0, b1));",
    "      if (dfGreater(hi, lo)) {",
    "        MF sgn = !dfLess(offset, DF_ZERO) ? DF_ONE : dfNeg(DF_ONE);",
    "        DVec2 normal = dv2Scale(perp, sgn);",
    "        MF penetration = dfSub(DF_LINE_THICKNESS, distP);",
    "        DVec2 pOnA0 = dv2Add(eA0, dv2Scale(dirA, lo));",
    "        DVec2 pOnA1 = dv2Add(eA0, dv2Scale(dirA, hi));",
    "        DVec2 halfOffset = dv2Scale(perp, dfMulPow2(offset, 0.5));",
    "        DVec2 pt0 = dv2Add(pOnA0, halfOffset);",
    "        result.c0.hit = true;",
    "        result.c0.normal = normal;",
    "        result.c0.point = pt0;",
    "        result.c0.rA = dv2Sub(pt0, dv2(lineA.x, lineA.y));",
    "        result.c0.rB = dv2Sub(pt0, dv2(lineB.x, lineB.y));",
    "        result.c0.penetration = penetration;",
    "        result.c0.tHit = DF_ZERO;",
    "        if (dfGreater(dfSub(hi, lo), DF_EPS6)) {",
    "          DVec2 pt1 = dv2Add(pOnA1, halfOffset);",
    "          result.c1.hit = true;",
    "          result.c1.normal = normal;",
    "          result.c1.point = pt1;",
    "          result.c1.rA = dv2Sub(pt1, dv2(lineA.x, lineA.y));",
    "          result.c1.rB = dv2Sub(pt1, dv2(lineB.x, lineB.y));",
    "          result.c1.penetration = penetration;",
    "          result.c1.tHit = DF_ZERO;",
    "        }",
    "        return result;",
    "      }",
    "    }",
    "  }",
    "",
    "  DClosestPair cp = dfClosestPointsSegmentSegment(gA, gB);",
    "  DVec2 d2v = dv2Sub(cp.c2, cp.c1);",
    "  MF dist2 = dv2Length(d2v);",
    "  if (!dfLess(dist2, DF_LINE_THICKNESS)) return result;",
    "  DVec2 n2 = dv2(DF_ZERO, DF_ONE);",
    "  if (dfGreater(dist2, DF_EPS9)) n2 = dv2Scale(d2v, dfDiv(DF_ONE, dist2));",
    "  DVec2 pt2 = dv2MulPow2(dv2Add(cp.c1, cp.c2), 0.5);",
    "  result.c0.hit = true;",
    "  result.c0.normal = n2;",
    "  result.c0.point = pt2;",
    "  result.c0.rA = dv2Sub(pt2, dv2(lineA.x, lineA.y));",
    "  result.c0.rB = dv2Sub(pt2, dv2(lineB.x, lineB.y));",
    "  result.c0.penetration = dfSub(DF_LINE_THICKNESS, dist2);",
    "  result.c0.tHit = DF_ZERO;",
    "  return result;",
    "}",
    "",
    "void dfApplyImpulse(inout DBody b, MF invMass, MF invInertia, DVec2 impulse, DVec2 r) {",
    "  b.vx = dfAdd(b.vx, dfMul(impulse.x, invMass));",
    "  b.vy = dfAdd(b.vy, dfMul(impulse.y, invMass));",
    "  b.w = dfAdd(b.w, dfMul(invInertia, dv2Cross(r, impulse)));",
    "}",
    "",
    "DVec2 dfVelocityAt(DBody b, DVec2 r) {",
    "  return dv2(dfSub(b.vx, dfMul(b.w, r.y)), dfAdd(b.vy, dfMul(b.w, r.x)));",
    "}",
    "",
    "// Everything about a contact that no solver iteration can change. Called",
    "// once per contact, right after detection. An anchored side's terms are zero.",
    "void dfPrepareContact(inout DContact c, MF invMassA, MF invInertiaA, bool movesA, MF invMassB, MF invInertiaB, bool movesB) {",
    "  if (!c.hit) return;",
    "  MF armA = DF_ZERO, armB = DF_ZERO;",
    "  if (movesA) armA = dfMul(dfSqr(dv2Cross(c.rA, c.normal)), invInertiaA);",
    "  if (movesB) armB = dfMul(dfSqr(dv2Cross(c.rB, c.normal)), invInertiaB);",
    "  c.invMassSum = dfAdd(dfAdd(invMassA, invMassB), dfAdd(armA, armB));",
    "  MF linearSum = dfAdd(invMassA, invMassB);",
    "  if (!dfGreater(linearSum, DF_ZERO)) return;",
    "  MF correction = dfMul(dfDiv(dfMax(dfSub(c.penetration, DF_POSITION_SLOP), DF_ZERO), linearSum), DF_POSITION_PERCENT);",
    "  if (movesA) c.pushA = dv2(dfMul(dfMul(c.normal.x, correction), invMassA), dfMul(dfMul(c.normal.y, correction), invMassA));",
    "  if (movesB) c.pushB = dv2(dfMul(dfMul(c.normal.x, correction), invMassB), dfMul(dfMul(c.normal.y, correction), invMassB));",
    "}",
    "",
    "// movesA/movesB are compile-time facts the generated step passes as",
    "// literals: false for an anchored body, whose inverse mass of zero turns",
    "// its half of the update into a multiply by zero.",
    "void dfSolveContactVelocity(inout DBody bodyA, MF invMassA, MF invInertiaA, bool movesA,",
    "                            inout DBody bodyB, MF invMassB, MF invInertiaB, bool movesB,",
    "                            DContact contact) {",
    "  if (!contact.hit) return;",
    "  DVec2 n = contact.normal;",
    "",
    // An anchored body's velocity is zero: nothing to rotate.
    "  DVec2 vA = dv2Zero(), vB = dv2Zero();",
    "  if (movesA) vA = dfVelocityAt(bodyA, contact.rA);",
    "  if (movesB) vB = dfVelocityAt(bodyB, contact.rB);",
    "  DVec2 rv = dv2Sub(vB, vA);",
    "  MF velAlongNormal = dv2Dot(rv, n);",
    "  if (dfGreater(velAlongNormal, DF_ZERO)) return;",
    "  if (!dfGreater(contact.invMassSum, DF_ZERO)) return;",
    "",
    "  MF e = dfSmoothstep(DF_HALF_RESTITUTION_THRESHOLD, DF_RESTITUTION_THRESHOLD, dfNeg(velAlongNormal));",
    "  MF j = dfDiv(dfNeg(dfMul(dfAdd(DF_ONE, e), velAlongNormal)), contact.invMassSum);",
    "  DVec2 impulse = dv2(dfMul(n.x, j), dfMul(n.y, j));",
    "  if (movesA) dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2Neg(impulse), contact.rA);",
    "  if (movesB) dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, contact.rB);",
    "  // Nothing along the tangent: every contact is frictionless.",
    "}",
    "",
    "void dfSolveContactPosition(inout DBody bodyA, bool movesA, inout DBody bodyB, bool movesB, DContact contact) {",
    "  if (!contact.hit) return;",
    "  if (movesA) { bodyA.x = dfSub(bodyA.x, contact.pushA.x); bodyA.y = dfSub(bodyA.y, contact.pushA.y); }",
    "  if (movesB) { bodyB.x = dfAdd(bodyB.x, contact.pushB.x); bodyB.y = dfAdd(bodyB.y, contact.pushB.y); }",
    "}",
    "",
    "// ---- The 2x2 effective-mass solve, split so its matrix can be kept ----",
    "struct DFactor2x2 { bool solvable; MF k11; MF k12; MF k22; MF invDet; };",
    "",
    "DFactor2x2 dfFactor2x2(MF mA, MF iA, DVec2 rA, MF mB, MF iB, DVec2 rB) {",
    "  DFactor2x2 k;",
    "  k.solvable = dfGreater(dfAdd(dfAdd(mA, mB), dfAdd(iA, iB)), DF_ZERO);",
    "  k.k11 = DF_ZERO; k.k12 = DF_ZERO; k.k22 = DF_ZERO; k.invDet = DF_ZERO;",
    "  if (!k.solvable) return k;",
    "  k.k11 = dfAdd(dfAdd(mA, mB), dfAdd(dfMul(iA, dfSqr(rA.y)), dfMul(iB, dfSqr(rB.y))));",
    "  k.k12 = dfSub(dfNeg(dfMul(iA, dfMul(rA.x, rA.y))), dfMul(iB, dfMul(rB.x, rB.y)));",
    "  k.k22 = dfAdd(dfAdd(mA, mB), dfAdd(dfMul(iA, dfSqr(rA.x)), dfMul(iB, dfSqr(rB.x))));",
    "  k.invDet = dfDiv(DF_ONE, dfSub(dfMul(k.k11, k.k22), dfSqr(k.k12)));",
    "  return k;",
    "}",
    "",
    "// The same matrix with side A immovable (mA = iA = 0): every A term is a",
    "// product with zero, so this is dfFactor2x2 with those terms deleted.",
    "DFactor2x2 dfFactor2x2OneSided(MF mB, MF iB, DVec2 rB) {",
    "  DFactor2x2 k;",
    "  k.solvable = dfGreater(dfAdd(mB, iB), DF_ZERO);",
    "  k.k11 = DF_ZERO; k.k12 = DF_ZERO; k.k22 = DF_ZERO; k.invDet = DF_ZERO;",
    "  if (!k.solvable) return k;",
    "  k.k11 = dfAdd(mB, dfMul(iB, dfSqr(rB.y)));",
    "  k.k12 = dfNeg(dfMul(iB, dfMul(rB.x, rB.y)));",
    "  k.k22 = dfAdd(mB, dfMul(iB, dfSqr(rB.x)));",
    "  k.invDet = dfDiv(DF_ONE, dfSub(dfMul(k.k11, k.k22), dfSqr(k.k12)));",
    "  return k;",
    "}",
    "",
    "DVec2 dfApply2x2(DFactor2x2 k, MF rhsX, MF rhsY) {",
    "  if (!k.solvable) return dv2Zero();",
    "  return dv2(dfMul(k.invDet, dfSub(dfMul(k.k22, rhsX), dfMul(k.k12, rhsY))),",
    "             dfMul(k.invDet, dfSub(dfMul(k.k11, rhsY), dfMul(k.k12, rhsX))));",
    "}",
    "",
    "// ---- Hinges ----",
    "//",
    "// snA/csA and snB/csB are each body's sin/cos, supplied by the caller.",
    "// No velocity iteration touches an angle, so the step computes the",
    "// rotated anchors and the factored matrix ONCE (dfPrepareHinge) and the",
    "// 8 iterations just apply them.",
    "struct DHingePre { DVec2 rA; DVec2 rB; DFactor2x2 k; };",
    "",
    "DHingePre dfPrepareHinge(MF invMassA, MF invInertiaA, DVec2 localAnchorA, MF snA, MF csA,",
    "                         MF invMassB, MF invInertiaB, DVec2 localAnchorB, MF snB, MF csB) {",
    "  DHingePre h;",
    "  h.rA = dv2RotateBy(localAnchorA, snA, csA);",
    "  h.rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  h.k = dfFactor2x2(invMassA, invInertiaA, h.rA, invMassB, invInertiaB, h.rB);",
    "  return h;",
    "}",
    "",
    "// Side A is the world pin: it never turns, so its anchor IS its lever",
    "// arm, and it never moves, so it drops out of the matrix.",
    "DHingePre dfPrepareWorldHinge(DVec2 anchorA, MF invMassB, MF invInertiaB, DVec2 localAnchorB, MF snB, MF csB) {",
    "  DHingePre h;",
    "  h.rA = anchorA;",
    "  h.rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  h.k = dfFactor2x2OneSided(invMassB, invInertiaB, h.rB);",
    "  return h;",
    "}",
    "",
    "void dfSolveHingeVelocity(inout DBody bodyA, MF invMassA, MF invInertiaA, bool movesA,",
    "                          inout DBody bodyB, MF invMassB, MF invInertiaB, bool movesB, DHingePre h) {",
    "  DVec2 vA = dv2Zero(), vB = dv2Zero();",
    "  if (movesA) vA = dfVelocityAt(bodyA, h.rA);",
    "  if (movesB) vB = dfVelocityAt(bodyB, h.rB);",
    "  DVec2 cdot = dv2Sub(vB, vA);",
    "  DVec2 impulse = dfApply2x2(h.k, dfNeg(cdot.x), dfNeg(cdot.y));",
    "  if (movesA) dfApplyImpulse(bodyA, invMassA, invInertiaA, dv2Neg(impulse), h.rA);",
    "  if (movesB) dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, h.rB);",
    "}",
    "",
    "// The pin's own velocity is zero, so the constraint velocity is just B's.",
    "void dfSolveWorldHingeVelocity(inout DBody bodyB, MF invMassB, MF invInertiaB, DHingePre h) {",
    "  DVec2 vB = dfVelocityAt(bodyB, h.rB);",
    "  DVec2 impulse = dfApply2x2(h.k, dfNeg(vB.x), dfNeg(vB.y));",
    "  dfApplyImpulse(bodyB, invMassB, invInertiaB, impulse, h.rB);",
    "}",
    "",
    "// Turn a body by delta and bring its carried sin/cos along: by the",
    "// short series when delta is small enough for it, from scratch when not.",
    "void dfTurn(inout MF angle, inout MF sn, inout MF cs, MF delta) {",
    "  angle = dfAdd(angle, delta);",
    OPTIONS.nudgeTrig
      ? "  if (!dfSinCosNudge(sn, cs, delta)) dfSinCos(angle, sn, cs);"
      : "  dfSinCos(angle, sn, cs);",
    "}",
    "",
    "// The position solve DOES rotate bodies, so unlike the velocity solver it",
    "// cannot be prepared once per step. Each body's sin/cos is instead",
    "// carried through the loop (inout) and advanced whenever this turns it.",
    "void dfSolveHingePosition(inout DBody bodyA, MF invMassA, MF invInertiaA, DVec2 localAnchorA, inout MF snA, inout MF csA, bool movesA,",
    "                          inout DBody bodyB, MF invMassB, MF invInertiaB, DVec2 localAnchorB, inout MF snB, inout MF csB, bool movesB) {",
    "  DVec2 rA = dv2RotateBy(localAnchorA, snA, csA);",
    "  DVec2 rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  DVec2 worldA = dv2Add(dv2(bodyA.x, bodyA.y), rA);",
    "  DVec2 worldB = dv2Add(dv2(bodyB.x, bodyB.y), rB);",
    "  DVec2 c = dv2Sub(worldB, worldA);",
    "  DVec2 impulse = dfApply2x2(dfFactor2x2(invMassA, invInertiaA, rA, invMassB, invInertiaB, rB), dfNeg(c.x), dfNeg(c.y));",
    "  if (movesA) {",
    "    bodyA.x = dfSub(bodyA.x, dfMul(impulse.x, invMassA));",
    "    bodyA.y = dfSub(bodyA.y, dfMul(impulse.y, invMassA));",
    "    dfTurn(bodyA.angle, snA, csA, dfNeg(dfMul(invInertiaA, dv2Cross(rA, impulse))));",
    "  }",
    "  if (movesB) {",
    "    bodyB.x = dfAdd(bodyB.x, dfMul(impulse.x, invMassB));",
    "    bodyB.y = dfAdd(bodyB.y, dfMul(impulse.y, invMassB));",
    "    dfTurn(bodyB.angle, snB, csB, dfMul(invInertiaB, dv2Cross(rB, impulse)));",
    "  }",
    "}",
    "",
    "void dfSolveWorldHingePosition(DVec2 anchorA, inout DBody bodyB, MF invMassB, MF invInertiaB, DVec2 localAnchorB, inout MF snB, inout MF csB) {",
    "  DVec2 rB = dv2RotateBy(localAnchorB, snB, csB);",
    "  DVec2 worldB = dv2Add(dv2(bodyB.x, bodyB.y), rB);",
    "  DVec2 c = dv2Sub(worldB, anchorA);",
    "  DVec2 impulse = dfApply2x2(dfFactor2x2OneSided(invMassB, invInertiaB, rB), dfNeg(c.x), dfNeg(c.y));",
    "  bodyB.x = dfAdd(bodyB.x, dfMul(impulse.x, invMassB));",
    "  bodyB.y = dfAdd(bodyB.y, dfMul(impulse.y, invMassB));",
    "  dfTurn(bodyB.angle, snB, csB, dfMul(invInertiaB, dv2Cross(rB, impulse)));",
    "}",
    ].join("\n");
  }

  global.PhysicsGPUDF = {
    // A getter: OPTIONS is read on every build.
    get GLSL_LIBRARY() { return buildLibrary(); },
    OPTIONS: OPTIONS,
  };
})(typeof window !== "undefined" ? window : globalThis);
